In [1]:
import pandas as pd
import numpy as np
import time

In [2]:
# parameters

# start_time = "2018-12-31 21:58:42"
end_time = "2019-01-01 11:58:42"
# generate this please
start_time = "?????"

time_frequency_for_periods__for_basic_data = "5T"
num_of_time_periods___for_basic_data = 24*20 # 24 hrs * 12 x 5 mins in each hour

# when generating time periods 
sampling_frequency = "3T"



# --- data urls 

curr_url = "????"
nordic_midnight_24_hrs_data__url = "/Users/miska/Documents/open_something/luftdaten/luftdaten_code/luftdaten__make_tabular_data__from_db_data/ld_NYE_midnight_24hrs_nordics_all_data_01.csv"

# set the current data source 
curr_url =nordic_midnight_24_hrs_data__url

In [3]:
# try convert the timestamp in the data, to epoch

in_data = pd.read_csv( curr_url )
in_data.shape

(127109, 7)

In [6]:
unique_sensor_ids = in_data['sensor_id'].unique()
unique_sensor_ids.shape

(205,)

In [7]:
unique_sensor_ids

array([ 7273,  7275,  7277,  7406,  7428,  7469,  7597,  8683,  9411,
        9436,  9743,  9797, 10216, 10250, 10281, 10430, 10647, 10721,
       10723, 10803, 10823, 10825, 10827, 10843, 10914, 10922, 10924,
       10926, 11002, 11004, 11006, 11058, 11232, 11374, 11376, 11378,
       11380, 11384, 11404, 11445, 11543, 11546, 11550, 11552, 11661,
       11663, 11763, 11765, 11767, 11769, 11771, 11773, 12120, 12124,
       12129, 12131, 12133, 12135, 12137, 12141, 12381, 12383, 12385,
       12387, 12389, 12391, 12393, 12663, 12673, 12679, 12687, 12691,
       12693, 12861, 12990, 12994, 13000, 13010, 13012, 13018, 13020,
       13307, 13419, 13421, 13423, 13425, 13428, 13441, 13443, 13475,
       13477, 13483, 13762, 14133, 14209, 14264, 14276, 14278, 14282,
       14290, 14292, 14294, 14296, 14722, 14797, 14799, 14801, 14803,
       14807, 14809, 14811, 14813, 14817, 14835, 14837, 14975, 15067,
       15069, 15071, 15073, 15549, 15551, 15561, 15837, 16147, 16149,
       16151, 16153, 16155, 16159, 16296, 16446, 16531, 16533, 16535,
       16537, 16705, 16723, 16811, 17018, 17020, 17038, 17235, 17351,
       17532, 17534, 17536, 17538, 17576, 17650, 17662, 17710, 17712,
       17923, 17925, 17927, 18056, 18110, 18112, 18243, 18590, 18820,
       18826, 18830, 18834, 18836, 18838, 18986, 19119, 19207, 19301,
       19337, 19547, 19597, 19599,  9368, 10234,  7499, 10719, 11659,
       12122, 12127, 14017, 14288, 10588, 12675, 14300, 16815, 11548,
       14984,  7426, 14284, 12681, 11657, 11402, 13014, 11060, 13479,
       16145, 11554, 17542,  9344, 18832, 16813,  5321])

In [10]:
sensor_7273_unique_rows = in_data[ in_data['sensor_id'] == 7273 ]
sensor_7273_unique_rows.shape

(716, 7)

In [11]:
sensor_7273_unique_rows

,sensor_id,sensor_namee,lat,lon,timestamp,p1,p2
0,7273,SDS011,60.002,17.846,2018-12-31 11:57:22,3.43,1.56
175,7273,SDS011,60.002,17.846,2018-12-31 11:59:50,3.78,1.55
346,7273,SDS011,60.002,17.846,2019-01-01 12:04:31,3.60,1.60
522,7273,SDS011,60.002,17.846,2019-01-01 12:07:00,2.47,1.44
700,7273,SDS011,60.002,17.846,2019-01-01 12:09:28,1.97,1.38
873,7273,SDS011,60.002,17.846,2019-01-01 12:11:57,1.87,1.25
1047,7273,SDS011,60.002,17.846,2019-01-01 12:16:54,2.60,1.59
1225,7273,SDS011,60.002,17.846,2019-01-01 12:19:25,1.98,1.48
1404,7273,SDS011,60.002,17.846,2019-01-01 12:21:53,2.24,1.28
1581,7273,SDS011,60.002,17.846,2019-01-01 12:24:22,3.32,1.52
1758,7273,SDS011,60.002,17.846,2019-01-01 12:26:50,2.52,1.38
1938,7273,SDS011,60.002,17.846,2019-01-01 12:31:47,1.72,1.20
2110,7273,SDS011,60.002,17.846,2019-01-01 12:34:16,2.14,1.05
2288,7273,SDS011,60.002,17.846,2019-01-01 12:36:47,2.54,1.10
2463,7273,SDS011,60.002,17.846,2019-01-01 12:39:16,2.18,1.20
2642,7273,SDS011,60.002,17.846,2019-01-01 12:41:44,1.95,1.15
2817,7273,SDS011,60.002,17.846,2019-01-01 12:46:41,1.78,1.03
2992,7273,SDS011,60.002,17.846,2019-01-01 12:49:10,1.48,0.94
3187,7273,SDS011,60.002,17.846,2019-01-01 12:54:07,1.88,1.05
3347,7273,SDS011,60.002,17.846,2019-01-01 12:56:35,1.97,1.15
3525,7273,SDS011,60.002,17.846,2019-01-01 13:01:35,1.63,0.95
3707,7273,SDS011,60.002,17.846,2019-01-01 13:04:07,1.46,0.97
3884,7273,SDS011,60.002,17.846,2019-01-01 13:06:35,2.44,1.15
4063,7273,SDS011,60.002,17.846,2019-01-01 13:09:04,2.98,1.18
4241,7273,SDS011,60.002,17.846,2019-01-01 13:11:33,2.48,1.05
4419,7273,SDS011,60.002,17.846,2019-01-01 13:16:40,1.64,0.98
4597,7273,SDS011,60.002,17.846,2019-01-01 13:19:09,2.25,0.95
4774,7273,SDS011,60.002,17.846,2019-01-01 13:21:44,2.48,0.99
4953,7273,SDS011,60.002,17.846,2019-01-01 13:24:31,2.27,0.95
5131,7273,SDS011,60.002,17.846,2019-01-01 13:27:00,1.37,0.82
...,...,...,...,...,...,...,...
121946,7273,SDS011,60.002,17.846,2019-01-01 10:32:47,3.85,1.86
122128,7273,SDS011,60.002,17.846,2019-01-01 10:37:44,3.83,1.76
122297,7273,SDS011,60.002,17.846,2019-01-01 10:40:16,3.63,1.72
122470,7273,SDS011,60.002,17.846,2019-01-01 10:42:44,3.43,1.76
122647,7273,SDS011,60.002,17.846,2019-01-01 10:45:13,3.32,1.96
122824,7273,SDS011,60.002,17.846,2019-01-01 10:47:44,4.00,1.98
122998,7273,SDS011,60.002,17.846,2019-01-01 10:52:44,2.97,1.62
123174,7273,SDS011,60.002,17.846,2019-01-01 10:55:12,3.32,1.85
123351,7273,SDS011,60.002,17.846,2019-01-01 10:57:41,4.37,2.00
123518,7273,SDS011,60.002,17.846,2019-01-01 11:00:09,4.05,2.00
123703,7273,SDS011,60.002,17.846,2019-01-01 11:02:38,4.30,1.95
123881,7273,SDS011,60.002,17.846,2019-01-01 11:07:35,3.50,1.72
124063,7273,SDS011,60.002,17.846,2019-01-01 11:10:03,2.42,1.64
124236,7273,SDS011,60.002,17.846,2019-01-01 11:12:32,2.60,1.68
124356,7273,SDS011,60.002,17.846,2019-01-01 11:15:00,4.60,1.66
124539,7273,SDS011,60.002,17.846,2019-01-01 11:22:26,3.60,1.62
124776,7273,SDS011,60.002,17.846,2019-01-01 11:19:57,4.16,1.59
125095,7273,SDS011,60.002,17.846,2019-01-01 11:24:54,3.46,1.65
125198,7273,SDS011,60.002,17.846,2019-01-01 11:27:23,2.76,1.50
125296,7273,SDS011,60.002,17.846,2019-01-01 11:29:51,2.88,1.50
125400,7273,SDS011,60.002,17.846,2019-01-01 11:34:49,2.76,1.54
125748,7273,SDS011,60.002,17.846,2019-01-01 11:37:17,2.33,1.64
125830,7273,SDS011,60.002,17.846,2019-01-01 11:39:45,2.35,1.55
126007,7273,SDS011,60.002,17.846,2019-01-01 11:42:15,3.08,1.50
126182,7273,SDS011,60.002,17.846,2019-01-01 11:44:44,3.62,1.40
126353,7273,SDS011,60.002,17.846,2019-01-01 11:49:40,3.46,1.65
126535,7273,SDS011,60.002,17.846,2019-01-01 11:52:09,3.01,1.56
126711,7273,SDS011,60.002,17.846,2019-01-01 11:54:37,2.54,1.55
126979,7273,SDS011,60.002,17.846,2019-01-01 11:57:06,3.20,1.50
127084,7273,SDS011,60.002,17.846,2019-01-01 11:59:34,2.63,1.30

In [12]:
sensor_7273_unique_rows[ sensor_7273_unique_rows['p1'] == 3.45 ]

       sensor_id sensor_namee     lat     lon            timestamp    p1    p2
44833       7273       SDS011  60.002  17.846  2018-12-31 12:07:16  3.45  1.75

In [14]:
sensor_7273_unique_rows__sorted_by_time = sensor_7273_unique_rows.sort_values( by=['timestamp'] )

In [16]:
%time sensor_7273_unique_rows__sorted_by_time

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 6.91 µs

       sensor_id sensor_namee     lat     lon            timestamp    p1    p2
0           7273       SDS011  60.002  17.846  2018-12-31 11:57:22  3.43  1.56
175         7273       SDS011  60.002  17.846  2018-12-31 11:59:50  3.78  1.55
44754       7273       SDS011  60.002  17.846  2018-12-31 12:04:47  4.12  1.90
44833       7273       SDS011  60.002  17.846  2018-12-31 12:07:16  3.45  1.75
42851       7273       SDS011  60.002  17.846  2018-12-31 12:09:44  2.10  1.36
45041       7273       SDS011  60.002  17.846  2018-12-31 12:12:13  1.45  1.16
43013       7273       SDS011  60.002  17.846  2018-12-31 12:14:43  2.02  1.28
45230       7273       SDS011  60.002  17.846  2018-12-31 12:19:43  1.78  1.36
43186       7273       SDS011  60.002  17.846  2018-12-31 12:22:12  2.00  1.36
43267       7273       SDS011  60.002  17.846  2018-12-31 12:24:40  2.45  1.42
43345       7273       SDS011  60.002  17.846  2018-12-31 12:27:09  2.58  1.55
43426       7273       SDS011  60.002  17.846  2018-12-31 12:27:09  2.58  1.55
43699       7273       SDS011  60.002  17.846  2018-12-31 12:29:37  3.67  1.80
45593       7273       SDS011  60.002  17.846  2018-12-31 12:29:37  3.67  1.80
43874       7273       SDS011  60.002  17.846  2018-12-31 12:34:35  2.30  1.88
44049       7273       SDS011  60.002  17.846  2018-12-31 12:37:03  2.80  1.84
44224       7273       SDS011  60.002  17.846  2018-12-31 12:39:32  2.74  1.75
44401       7273       SDS011  60.002  17.846  2018-12-31 12:42:00  3.00  1.80
44579       7273       SDS011  60.002  17.846  2018-12-31 12:46:57  2.95  1.83
47741       7273       SDS011  60.002  17.846  2018-12-31 12:49:26  2.46  1.75
47825       7273       SDS011  60.002  17.846  2018-12-31 12:51:54  3.20  1.60
47910       7273       SDS011  60.002  17.846  2018-12-31 12:54:23  3.28  1.50
47987       7273       SDS011  60.002  17.846  2018-12-31 12:56:51  2.14  1.46
46035       7273       SDS011  60.002  17.846  2018-12-31 13:01:48  2.35  1.42
46124       7273       SDS011  60.002  17.846  2018-12-31 13:04:17  2.25  1.28
46199       7273       SDS011  60.002  17.846  2018-12-31 13:06:45  2.50  1.36
48357       7273       SDS011  60.002  17.846  2018-12-31 13:09:14  2.04  1.45
46374       7273       SDS011  60.002  17.846  2018-12-31 13:11:42  2.11  1.40
48517       7273       SDS011  60.002  17.846  2018-12-31 13:16:47  2.25  1.62
46578       7273       SDS011  60.002  17.846  2018-12-31 13:19:17  2.22  1.64
...          ...          ...     ...     ...                  ...   ...   ...
36287       7273       SDS011  60.002  17.846  2019-01-01 22:31:21  1.64  1.28
36463       7273       SDS011  60.002  17.846  2019-01-01 22:33:55  1.60  1.20
36639       7273       SDS011  60.002  17.846  2019-01-01 22:36:26  2.43  1.32
36814       7273       SDS011  60.002  17.846  2019-01-01 22:38:57  3.85  1.52
36987       7273       SDS011  60.002  17.846  2019-01-01 22:41:30  4.04  1.35
37162       7273       SDS011  60.002  17.846  2019-01-01 22:46:33  2.55  1.38
37340       7273       SDS011  60.002  17.846  2019-01-01 22:49:03  2.88  1.45
37520       7273       SDS011  60.002  17.846  2019-01-01 22:51:32  3.55  1.45
37697       7273       SDS011  60.002  17.846  2019-01-01 22:54:00  4.05  1.35
37874       7273       SDS011  60.002  17.846  2019-01-01 22:56:29  3.56  1.35
38050       7273       SDS011  60.002  17.846  2019-01-01 23:01:27  3.62  1.25
38225       7273       SDS011  60.002  17.846  2019-01-01 23:04:04  3.12  1.18
38398       7273       SDS011  60.002  17.846  2019-01-01 23:06:38  2.93  1.34
38575       7273       SDS011  60.002  17.846  2019-01-01 23:09:07  3.57  1.30
41889       7273       SDS011  60.002  17.846  2019-01-01 23:11:35  3.18  1.14
39642       7273       SDS011  60.002  17.846  2019-01-01 23:16:32  4.22  1.28
42066       7273       SDS011  60.002  17.846  2019-01-01 23:19:04  3.28  1.23
39829       7273       SDS011  60.002  17.846  2019-01-01 23:21:36  3.64  1.45
39915       7273       SDS011  60.002  17.846  2019-01-01 23:24:05  3.66  1.56
39989       7273       SDS011  60.002  17.846  2019-01-01 23:26:33  5.98  1.65
42429       7273       SDS011  60.002  17.846  2019-01-01 23:31:30  4.80  1.36
40172       7273       SDS011  60.002  17.846  2019-01-01 23:33:59  3.68  1.18
40257       7273       SDS011  60.002  17.846  2019-01-01 23:36:27  3.73  1.08
40347       7273       SDS011  60.002  17.846  2019-01-01 23:38:56  4.75  1.25
40524       7273       SDS011  60.002  17.846  2019-01-01 23:41:33  3.35  1.15
40704       7273       SDS011  60.002  17.846  2019-01-01 23:46:33  2.88  1.10
40884       7273       SDS011  60.002  17.846  2019-01-01 23:46:33  2.88  1.10
41061       7273       SDS011  60.002  17.846  2019-01-01 23:51:36  3.49  1.12
41238       7273       SDS011  60.002  17.846  2019-01-01 23:54:04  2.90  1.22
41418       7273       SDS011  60.002  17.846  2019-01-01 23:56:33  4.14  1.48

[716 rows x 7 columns]