In [1]:
import pandas as pd
import numpy as np
import time

In [2]:
# parameters

# start_time = "2018-12-31 21:58:42"
end_time = "2019-01-01 11:58:42"
# generate this please
start_time = "?????"

time_frequency_for_periods__for_basic_data = "5T"
num_of_time_periods___for_basic_data = 24*20 # 24 hrs * 12 x 5 mins in each hour

# when generating time periods 
sampling_frequency = "3T"



# --- data urls 

curr_url = "????"
nordic_midnight_24_hrs_data__url = "/Users/miska/Documents/open_something/luftdaten/luftdaten_code/luftdaten__make_tabular_data__from_db_data/ld_NYE_midnight_24hrs_nordics_all_data_01.csv"

# set the current data source 
curr_url =nordic_midnight_24_hrs_data__url

In [3]:
# try convert the timestamp in the data, to epoch

in_data = pd.read_csv( curr_url )
in_data.shape

(127109, 7)

In [4]:
in_data.dtypes

sensor_id         int64
sensor_namee     object
lat             float64
lon             float64
timestamp        object
p1              float64
p2              float64
dtype: object

In [5]:
in_data['timestamp'] = pd.to_datetime( in_data['timestamp'] )

In [6]:
in_data.head()

   sensor_id sensor_namee     lat     lon           timestamp      p1     p2
0       7273       SDS011  60.002  17.846 2018-12-31 11:57:22    3.43   1.56
1       7275       SDS011  57.720  11.888 2018-12-31 11:58:44  482.77  33.82
2       7277       SDS011  59.266  15.230 2018-12-31 11:58:47    5.48   2.47
3       7406       SDS011  56.964  24.128 2018-12-31 11:56:41   11.05   6.62
4       7428       SDS011  59.868  17.624 2018-12-31 11:57:42    1.78   1.02

In [7]:
in_data.tail()

,sensor_id,sensor_namee,lat,lon,timestamp,p1,p2
127104,16723,SDS011,57.736,11.894,2019-01-01 11:58:57,16.47,3.40
127105,16815,SDS011,59.462,18.040,2019-01-01 11:59:36,2.67,1.97
127106,17235,SDS011,59.272,17.780,2019-01-01 11:59:41,4.69,1.82
127107,10588,SDS011,55.676,13.346,2019-01-01 11:57:12,14.08,3.68
127108,10647,SDS011,55.608,13.036,2019-01-01 11:58:42,23.42,4.75

In [8]:
in_data2 = in_data.copy()

In [9]:
in_data2['timestamp'] = in_data['timestamp'].astype( 'int64' )

In [10]:
in_data2.head()

   sensor_id sensor_namee     lat     lon            timestamp      p1     p2
0       7273       SDS011  60.002  17.846  1546257442000000000    3.43   1.56
1       7275       SDS011  57.720  11.888  1546257524000000000  482.77  33.82
2       7277       SDS011  59.266  15.230  1546257527000000000    5.48   2.47
3       7406       SDS011  56.964  24.128  1546257401000000000   11.05   6.62
4       7428       SDS011  59.868  17.624  1546257462000000000    1.78   1.02

In [11]:
in_data2.tail()

,sensor_id,sensor_namee,lat,lon,timestamp,p1,p2
127104,16723,SDS011,57.736,11.894,1546343937000000000,16.47,3.40
127105,16815,SDS011,59.462,18.040,1546343976000000000,2.67,1.97
127106,17235,SDS011,59.272,17.780,1546343981000000000,4.69,1.82
127107,10588,SDS011,55.676,13.346,1546343832000000000,14.08,3.68
127108,10647,SDS011,55.608,13.036,1546343922000000000,23.42,4.75

In [12]:
### various time operations

In [13]:
end_time

'2019-01-01 11:58:42'

In [14]:
# generate the time slots when the data is sampled

data_sampling_windows__time_periods = pd.date_range( end_time, freq=sampling_frequency,  
periods=num_of_time_periods___for_basic_data+1)

In [15]:
# check generated times
data_sampling_windows__time_periods

DatetimeIndex(['2019-01-01 11:58:42', '2019-01-01 12:01:42',
               '2019-01-01 12:04:42', '2019-01-01 12:07:42',
               '2019-01-01 12:10:42', '2019-01-01 12:13:42',
               '2019-01-01 12:16:42', '2019-01-01 12:19:42',
               '2019-01-01 12:22:42', '2019-01-01 12:25:42',
               ...
               '2019-01-02 11:31:42', '2019-01-02 11:34:42',
               '2019-01-02 11:37:42', '2019-01-02 11:40:42',
               '2019-01-02 11:43:42', '2019-01-02 11:46:42',
               '2019-01-02 11:49:42', '2019-01-02 11:52:42',
               '2019-01-02 11:55:42', '2019-01-02 11:58:42'],
              dtype='datetime64[ns]', length=481, freq='3T')

In [16]:
# then to 'go back in time' from the end date

# adding the '+1' to avoid the off by one errors  
data_sampling_windows__time_periods = data_sampling_windows__time_periods - ( num_of_time_periods___for_basic_data
 + 1 )

In [17]:
data_sampling_windows__time_periods[0]

Timestamp('2018-12-31 11:55:42', freq='3T')

In [18]:
data_sampling_windows__time_periods

DatetimeIndex(['2018-12-31 11:55:42', '2018-12-31 11:58:42',
               '2018-12-31 12:01:42', '2018-12-31 12:04:42',
               '2018-12-31 12:07:42', '2018-12-31 12:10:42',
               '2018-12-31 12:13:42', '2018-12-31 12:16:42',
               '2018-12-31 12:19:42', '2018-12-31 12:22:42',
               ...
               '2019-01-01 11:28:42', '2019-01-01 11:31:42',
               '2019-01-01 11:34:42', '2019-01-01 11:37:42',
               '2019-01-01 11:40:42', '2019-01-01 11:43:42',
               '2019-01-01 11:46:42', '2019-01-01 11:49:42',
               '2019-01-01 11:52:42', '2019-01-01 11:55:42'],
              dtype='datetime64[ns]', length=481, freq='3T')

In [35]:
data_sampling_windows__time_periods.shape

(481,)

In [19]:
end_time = pd.to_datetime( end_time )
end_time

Timestamp('2019-01-01 11:58:42')

In [20]:
start_time = data_sampling_windows__time_periods[0]
start_time

Timestamp('2018-12-31 11:55:42', freq='3T')

In [21]:
### Fetch relevant time period, of data from csv 

relev_time_period = in_data[ in_data['timestamp'] >= start_time ]
relev_time_period = relev_time_period[ relev_time_period['timestamp'] < end_time ]


in_data.shape, relev_time_period.shape

((127109, 7), (84702, 7))

In [22]:
relev_time_period.head()

   sensor_id sensor_namee     lat     lon           timestamp      p1     p2
0       7273       SDS011  60.002  17.846 2018-12-31 11:57:22    3.43   1.56
1       7275       SDS011  57.720  11.888 2018-12-31 11:58:44  482.77  33.82
2       7277       SDS011  59.266  15.230 2018-12-31 11:58:47    5.48   2.47
3       7406       SDS011  56.964  24.128 2018-12-31 11:56:41   11.05   6.62
4       7428       SDS011  59.868  17.624 2018-12-31 11:57:42    1.78   1.02

In [23]:
relev_time_period.tail()

,sensor_id,sensor_namee,lat,lon,timestamp,p1,p2
127083,19301,SDS011,59.362,12.152,2019-01-01 11:56:50,0.02,0.00
127097,12990,SDS011,57.692,11.958,2019-01-01 11:58:00,16.63,3.60
127101,16153,SDS011,55.648,13.208,2019-01-01 11:57:19,20.00,3.90
127103,16533,SDS011,55.722,13.202,2019-01-01 11:56:55,18.05,4.33
127107,10588,SDS011,55.676,13.346,2019-01-01 11:57:12,14.08,3.68

In [24]:
# --- now loop through the different sensor datas

In [25]:
unique_sensor_ids = relev_time_period['sensor_id'].unique()
unique_sensor_ids.shape

(200,)

In [70]:
# temporary storage location for out arrays 
out_array_w_generated_periodic_data_arrays = []

# prepare the out array, beforhand
## curr_sensor_measurements_for_all_time_periods = np.zeros( data_sampling_windows__time_periods.shape[0] )

curr_sensor_id_i = 0

starttime = time.time() 

# Loop through the different sensor ( numbers )
for sensor_id_ in unique_sensor_ids[:10]:
    print("-- working on sensor id "+str( sensor_id_ )+" |  "+str( curr_sensor_id_i )+"/"+str( unique_sensor_ids.shape[0] )  )
    curr_sensor_id_i = curr_sensor_id_i + 1
    
    # fetch the measurements for this sensor id
    curr_sensor_id_measurements = relev_time_period[ relev_time_period['sensor_id'] == sensor_id_  ]
    
    # sort them by time 
    curr_sensor_id_measurements = curr_sensor_id_measurements.sort_values( by=['timestamp'] ) 
    ## print("--- current sensor id has "+str( curr_sensor_id_measurements.shape[0])+" measurements" )
    
    curr_sensor_id_measurements__only_timestamps = curr_sensor_id_measurements['timestamp']
    curr_sensor_id_measurements__only_p1_vals = curr_sensor_id_measurements['p1']
    curr_sensor_id_measurements__only_p2_vals = curr_sensor_id_measurements['p2']
    
    # -- make sure all the measurements of the given time period are there
    
    # make an array with enough slots for all time periods
    curr_sensor_measurements_for_all_time_periods = np.zeros( data_sampling_windows__time_periods.shape[0] )
    ## print(" --- curr_sensor_measurements_for_all_time_periods.shape = "+str( curr_sensor_measurements_for_all_time_periods.shape ))
    ## print( curr_sensor_measurements_for_all_time_periods )
    
    # loop through all values in the data 
    for curr_sensor_measurements_row_i in range( curr_sensor_id_measurements__only_timestamps.shape[0] ):
    ### for curr_sensor_measurements_row_i in range( 10 ):
        ## print("\n-- -- working on measurement #"+str( curr_sensor_measurements_row_i )+" (pm2.5/10  : "+str(curr_sensor_id_measurements__only_p1_vals.iloc[ curr_sensor_measurements_row_i])+"/"+str(curr_sensor_id_measurements__only_p2_vals.iloc[ curr_sensor_measurements_row_i])+") - with timestamp "+str( curr_sensor_id_measurements__only_timestamps.iloc[ curr_sensor_measurements_row_i ] ) )
        
        # loop through the available timestamps, and see whether the current time stamp
        # is within these. 
        # - if it is, then insert it at the appropiate current index 
        # in the out array
        
        # optimisation variable to remember where the last 
        # value was found, in time
        # - the idea is that we start the next search in time indicies, 
        #   only after the last found position, so we can skip checking the previous positions 
        last_found_time_index = 0 
        # note the optimisation above and below 
        for all_relev_timestamps_array__current_index in range( last_found_time_index, data_sampling_windows__time_periods.shape[0]-1 ):
        ### unoptimised edition : 
        ### for all_relev_timestamps_array__current_index in range( data_sampling_windows__time_periods.shape[0]-1 ):
        ### for all_relev_timestamps_array__current_index in range( 100 ):
        
            # print("-- -- -- looping through available timestamps - loooking at index #"+str( all_relev_timestamps_array__current_index )+" : timestamp "+str( data_sampling_windows__time_periods[ all_relev_timestamps_array__current_index ] ))
            #
            if curr_sensor_id_measurements__only_timestamps.iloc[ curr_sensor_measurements_row_i ] > data_sampling_windows__time_periods[ all_relev_timestamps_array__current_index ] and curr_sensor_id_measurements__only_timestamps.iloc[ curr_sensor_measurements_row_i ] < data_sampling_windows__time_periods[ all_relev_timestamps_array__current_index+1 ]:
                
                ## print(" -- -- -- -- YAY! the current timestamp ( "+str(  curr_sensor_id_measurements__only_timestamps.iloc[ curr_sensor_measurements_row_i ]  )+" is within the specified time ranges, at index "+str( all_relev_timestamps_array__current_index )+" amongst the possible time periods data. ie. btw "+str( data_sampling_windows__time_periods[ all_relev_timestamps_array__current_index ])+" and "+str( data_sampling_windows__time_periods[ all_relev_timestamps_array__current_index ]+1 ) )
                # 
                # assign the current PM value as appropriate 
                curr_sensor_measurements_for_all_time_periods[ all_relev_timestamps_array__current_index ] = curr_sensor_id_measurements__only_p1_vals.iloc[ curr_sensor_measurements_row_i ]
                
                # set the variable suggesting which position 
                # the timestamp was found in, 
                # and which position the next search should start from 
                last_found_time_index = all_relev_timestamps_array__current_index
                
                #
                # no need to continue finding possible time slots - just break
                break
                
    # END OF DIFFERENT SENSOR LOOPING
    # print the resulting values slotted array - ie array with slots 
    # for values, formatted according to time slots
    ## print( " <<< resulting periodic values array : ")
    ## print( curr_sensor_measurements_for_all_time_periods )
    out_array_w_generated_periodic_data_arrays.append( curr_sensor_measurements_for_all_time_periods )
                
# ende
print( "- done after "+str( time.time() - starttime )+" seconds " )

-- working on sensor id 7273 |  0/200
-- working on sensor id 7275 |  1/200
-- working on sensor id 7277 |  2/200
-- working on sensor id 7406 |  3/200
-- working on sensor id 7428 |  4/200
-- working on sensor id 7469 |  5/200
-- working on sensor id 7597 |  6/200
-- working on sensor id 8683 |  7/200
-- working on sensor id 9411 |  8/200
-- working on sensor id 9436 |  9/200
- done after 56.7964563369751 seconds

In [71]:
curr_sensor_measurements_for_all_time_periods

array([ 2.12,  3.04,  0.  ,  2.06,  3.  ,  3.34,  0.  ,  3.48,  3.16,
        3.25,  3.14,  1.92,  2.32,  2.42,  2.32,  0.  ,  3.38,  3.1 ,
        3.02,  2.22,  2.33,  1.8 ,  2.34,  2.99,  0.  ,  2.4 ,  1.74,
        1.82,  0.  ,  1.45,  1.94,  3.16,  3.8 ,  1.3 ,  1.98,  3.25,
        3.72,  0.  ,  3.25,  2.62,  2.62,  0.  ,  3.1 ,  2.8 ,  2.8 ,
        2.06,  1.46,  2.22,  2.38,  1.92,  0.  ,  3.26,  2.84,  2.12,
        2.18,  5.03,  5.65,  2.54,  2.08,  0.  ,  1.62,  1.7 ,  1.78,
        0.  ,  2.82,  1.84,  1.64,  2.24,  2.55,  2.53,  4.48,  4.07,
        0.  ,  2.58,  2.2 ,  1.82,  2.3 ,  2.45,  3.35,  2.58,  1.56,
        0.  ,  1.75,  2.86,  0.  ,  3.7 ,  0.  ,  3.76,  3.98,  3.5 ,
        0.  ,  2.68,  2.65,  2.76,  3.12,  0.  ,  2.56,  3.22,  3.06,
        2.37,  4.05,  2.54,  2.88,  2.48,  0.  ,  3.55,  3.45,  5.25,
        0.  ,  5.23,  0.  ,  6.17,  5.5 ,  0.  ,  7.45,  6.62,  4.58,
        3.22,  3.86,  3.57,  2.63,  2.46,  0.  ,  2.42,  2.53,  2.48,
        2.78,  2.75,  3.15,  3.62,  3.8 ,  2.44,  3.5 ,  4.72,  5.05,
        0.  ,  2.65,  3.47,  4.85,  4.83,  4.77,  4.46,  3.84,  3.75,
        0.  ,  4.08,  3.68,  3.05,  0.  ,  4.25,  4.3 ,  4.07,  4.99,
        4.51,  3.65,  3.84,  5.46,  0.  ,  4.24,  5.02,  4.28,  3.88,
        5.58,  4.07,  4.1 ,  5.4 ,  0.  ,  9.4 ,  6.42,  5.72,  0.  ,
        6.75,  5.55,  5.32,  6.52,  8.98,  7.32,  8.22,  8.07,  0.  ,
        5.22,  7.22,  7.37,  7.1 ,  8.43,  9.07,  9.27,  8.72,  0.  ,
        5.95,  7.32,  7.7 ,  0.  ,  7.76,  9.1 ,  8.97,  6.78,  7.22,
        7.15,  6.54,  8.67,  0.  , 15.6 , 14.25,  8.38,  8.65,  6.64,
        9.09,  9.  ,  7.06,  0.  ,  8.07,  6.63,  0.  ,  6.77,  0.  ,
        5.02,  5.12,  5.07,  0.  , 17.92, 19.87, 18.35, 20.46, 22.1 ,
       29.75, 35.3 , 39.57,  0.  , 35.62, 32.05, 27.4 , 24.5 , 27.57,
       26.32, 26.24, 28.78,  0.  , 31.38, 29.84, 30.85,  0.  , 22.94,
       19.72, 19.42, 17.37, 13.84, 14.14, 12.84, 11.58,  0.  , 10.43,
       12.28, 11.68,  9.86,  9.7 ,  9.8 , 10.04,  9.57,  0.  ,  8.12,
        8.16,  8.93,  0.  ,  7.25,  6.75,  7.7 ,  8.09,  7.54,  7.92,
        7.36,  8.12,  0.  ,  7.94,  5.68,  6.22,  7.6 ,  7.64,  7.28,
        7.28,  7.72,  0.  ,  7.82,  8.15, 10.45,  0.  ,  5.15,  6.52,
        8.4 ,  6.28,  6.85,  6.32,  7.  ,  6.18,  0.  ,  9.85,  7.82,
        6.7 ,  5.7 ,  8.13, 10.76,  8.  ,  4.77,  6.04,  7.57, 10.  ,
        7.93,  0.  ,  8.56,  9.38,  8.05,  7.22, 10.67,  0.  ,  6.93,
        7.46,  7.52,  0.  , 11.2 , 10.57,  8.4 ,  7.45,  8.84,  7.48,
        7.5 ,  8.86,  0.  , 10.14, 10.15,  7.98,  0.  ,  8.06,  7.93,
        9.41, 10.52,  7.32,  6.52,  6.24,  5.37,  0.  ,  8.76, 12.57,
       12.04,  8.14,  6.4 ,  5.83,  6.9 ,  6.42,  0.  ,  7.96,  7.9 ,
        7.44,  0.  ,  7.72,  5.34,  6.22,  6.8 ,  4.36,  6.28,  6.92,
        6.55,  0.  ,  4.93,  6.86,  7.95,  6.34,  5.22,  4.31,  3.66,
        5.18,  6.48,  6.12,  3.58,  2.96,  0.  ,  5.55,  5.42,  5.32,
        4.58,  3.66,  3.62,  5.85,  4.66,  2.68,  0.  ,  3.76,  2.84,
        3.22,  0.  ,  3.58,  3.75,  3.04,  1.78,  3.57,  2.88,  3.86,
        4.46,  0.  ,  3.04,  3.2 ,  3.95,  4.88,  3.6 ,  2.84,  3.87,
        4.47,  0.  ,  3.04,  4.07,  4.18,  0.  ,  3.96,  3.05,  4.05,
        4.05,  4.78,  5.75,  6.06,  6.6 ,  0.  ,  4.25,  4.22,  3.4 ,
        3.25,  4.1 ,  3.7 ,  2.77,  2.05,  3.49,  3.78,  5.38,  3.75,
        0.  ,  3.67,  2.65,  2.86,  2.76,  2.04,  2.34,  3.28,  4.  ,
        0.  ,  2.54,  2.1 ,  1.9 ,  2.15,  4.26,  4.33,  4.81,  3.08,
        0.  ,  2.45,  1.82,  2.01,  0.  ,  2.22,  2.32,  3.24,  4.5 ,
        3.54,  4.65,  4.28,  2.66,  0.  ,  4.38,  4.6 ,  3.58,  2.05,
        1.88,  2.08,  3.32,  3.13,  0.  ,  2.44,  2.58,  1.55,  0.  ,
        3.12,  2.38,  3.54,  0.  ])

In [72]:
len( out_array_w_generated_periodic_data_arrays )

10

In [73]:
out_array_w_generated_periodic_data_arrays

[array([  3.43,   3.78,   0.  ,   3.45,   2.1 ,   1.45,   2.02,   0.  ,
          2.  ,   2.45,   2.58,   3.67,   2.3 ,   2.8 ,   2.74,   3.  ,
          0.  ,   2.46,   3.2 ,   3.28,   2.14,   0.  ,   2.25,   2.5 ,
          2.04,   2.11,   0.  ,   2.22,   2.16,   3.43,   3.92,   0.  ,
          3.67,   3.43,   3.78,   3.47,   0.  ,   3.95,   3.7 ,   4.3 ,
          3.68,   3.35,   3.54,   2.82,   2.78,   3.18,   3.8 ,   3.7 ,
          3.17,   2.48,   0.  ,  24.2 ,  28.6 ,  36.15,  56.58,   0.  ,
          9.7 ,  11.85,   7.  ,   6.12,   0.  ,   6.96,   3.76,   7.76,
         28.13,  13.18,   4.42,   5.92,   6.25,   0.  , 455.  , 569.68,
        128.9 ,  16.56,   0.  ,  11.36,  13.7 ,  23.78,  22.02,  14.3 ,
          8.06,   2.62,   3.1 ,   4.08,   2.15,   2.06,   3.2 ,   3.8 ,
          0.  ,   3.6 ,   3.65,   2.85,   2.37,   0.  ,   0.  , 157.77,
        107.95,  77.23,  76.95,  33.72,  42.24,  18.16,   9.18,   0.  ,
         13.89,  38.6 ,  96.7 ,  71.92,   0.  ,  31.08,   8.12,   6.35,
          3.88,   0.  ,   3.04,   2.77,  39.67,  41.94,  32.36,  26.32,
         28.72,  26.3 ,   0.  ,   7.3 ,   7.02,   7.98,  11.05,   0.  ,
          2.4 ,   2.4 ,   2.14,   1.8 ,   1.6 ,   1.34,   1.56,   1.85,
          1.58,   1.8 ,   1.65,   1.84,   1.97,   2.17,   1.95,   2.77,
          2.18,   1.76,   2.4 ,   0.  ,   2.94,   3.84,   3.67,   2.5 ,
          0.  ,   2.48,   2.35,   2.  ,   2.67,   3.15,   3.8 ,   3.04,
          2.32,   0.  ,   3.85,   2.98,   3.94,   4.05,   0.  ,   4.31,
          3.78,   4.03,   4.98,   0.  ,   6.04,   6.8 ,   8.86,   7.83,
          5.43,   6.3 ,   6.98,   6.38,   0.  ,   7.65,   7.12,   7.22,
          7.74,   0.  ,   6.02,   8.55,  10.76,  11.03,   0.  ,   7.88,
          8.02,   8.9 ,   9.88,   0.  ,   9.38,   9.02,   9.75,  10.4 ,
         12.32,  13.94,  11.4 ,  10.14,  11.58,  11.54,  10.88,  10.07,
          9.32,   0.  ,   9.9 ,  10.65,   9.1 ,   9.35,   0.  ,   8.02,
          6.4 ,   9.09,  11.5 ,   0.  ,   8.09,  11.17,  11.88,  10.25,
          0.  ,  10.1 ,   8.38,   6.84,   9.78,   0.  ,   8.76,  12.02,
         12.25,   9.96,   0.  ,   9.88,  10.75,   9.92,   9.48,   0.  ,
          8.4 ,   8.64,  10.35,  11.46,   0.  ,   8.59,   6.48,   8.18,
          9.35,   7.47,   6.62,  10.  ,  10.68,   0.  ,   8.78,   9.65,
          7.68,   6.22,   0.  ,   8.6 ,   9.26,   9.05,   6.98,   7.38,
          7.42,   9.91,   8.88,   0.  ,   9.44,   6.85,   8.34,  11.32,
          0.  ,  11.65,   8.24,   9.05,   8.91,   0.  ,  10.88,   9.83,
          9.22,   9.35,  10.  ,   9.8 ,   7.52,   9.  ,   0.  ,   9.25,
          8.23,   9.28,   9.  ,   0.  ,   9.1 ,   9.05,   9.62,  12.72,
         11.82,  10.1 ,  10.05,  12.78,   0.  ,   8.4 ,   7.97,   7.1 ,
          7.43,   0.  ,   9.98,  11.08,  13.4 ,  12.86,   0.  ,   9.37,
          9.9 ,   9.5 ,   9.27,   7.98,   7.74,   8.04,   7.74,   0.  ,
         10.24,   7.94,   8.35,   9.32,   0.  ,   8.  ,   8.65,   9.68,
          7.1 ,   6.72,   6.42,   5.92,   6.44,   0.  ,   8.08,   6.55,
          6.74,   7.36,   0.  ,   7.35,   7.27,   7.02,   6.22,   6.56,
          5.78,   4.42,   6.  ,   6.9 ,   5.78,   5.12,   4.66,   6.53,
          0.  ,   7.78,   9.12,   7.43,   5.15,   0.  ,   6.32,   6.92,
          6.26,   4.98,   0.  ,   5.01,   4.51,   4.68,   5.98,   7.12,
          6.  ,   5.86,   5.9 ,   0.  ,   6.15,   3.7 ,   3.44,   4.49,
          0.  ,   4.19,   3.38,   3.95,   3.9 ,   4.72,   5.4 ,   3.5 ,
          4.  ,   4.66,   5.1 ,   8.25,   8.38,   0.  ,   5.86,   0.  ,
          3.05,   4.05,   4.53,   3.58,   0.  ,   5.66,   5.07,   3.55,
          3.8 ,   6.12,   3.5 ,   3.08,   5.04,   4.6 ,   4.31,   5.24,
          4.04,   3.42,   0.  ,   3.53,   3.82,   3.18,   2.95,   0.  ,
          4.23,   4.03,   3.78,   3.96,   3.9 ,   6.24,   5.76,   3.42,
          0.  ,   4.07,   3.2 ,   3.53,   3.56,   0.  ,   3.04,   3.1 ,
          4.13,   3.66,   0.  ,   4.14,   3.84,   4.3 ,   4.88,   5.62,
          6.62,   5.66,   5.92,   6.26,   4.65,   4.52,   4.4 ,   4.2 ,
          0.  ,   3.06,   3.88,   3.87,   3.85,   0.  ,   3.63,   3.43,
          3.32,   4.  ,   0.  ,   3.32,   4.37,   4.05,   4.3 ,   3.5 ,
          2.42,   2.6 ,   4.6 ,   0.  ,   3.6 ,   3.46,   2.76,   2.88,
          0.  ,   2.33,   2.35,   3.08,   3.62,   3.46,   3.01,   2.54,
          0.  ]),
 array([  0.  , 455.92, 521.07, 440.7 ,   0.  ,   0.  , 486.08, 454.58,
        476.68, 409.68, 357.93, 288.47, 272.86, 330.58,   0.  , 232.87,
        226.2 , 248.13, 252.7 , 293.52, 262.68, 180.5 , 230.5 ,   0.  ,
         73.34,  46.04,  27.47,  24.52,  26.18,  21.85,  24.08,  27.58,
          0.  ,  30.64,  30.14,  33.15,  34.32,  26.94,  27.38,  27.87,
         24.82,   0.  ,  27.4 ,  27.15,  25.38,  27.03,   0.  ,  28.74,
         30.18,  25.38,   0.  ,  26.37,  28.52,  30.38,  28.76,   0.  ,
         26.62,  28.84,  29.22,  29.75,  28.54,  27.87,  26.1 ,  21.58,
          0.  ,  21.08,  28.72,  40.84,  64.75,  84.25, 153.63, 290.62,
        305.45,   0.  , 211.85, 220.26, 359.7 , 368.94, 314.8 , 242.53,
        261.62, 291.3 ,   0.  , 394.9 , 467.74, 519.48, 490.  , 463.4 ,
        499.86, 580.  , 500.  ,   0.  , 390.55, 400.96, 429.66, 381.65,
        282.83, 304.06, 278.15, 172.96,   0.  , 415.42, 367.73, 352.86,
        293.84,   0.  ,  35.94,  26.4 ,  26.92,   0.  ,  26.16,  28.6 ,
         32.37,  32.82,   0.  ,  29.4 ,  33.56,  37.25,  36.72,  34.67,
          0.  ,   0.  ,  45.97,  39.68,   0.  ,  30.9 ,  35.56,  36.92,
         35.03,  34.52,  35.18,  33.15,  38.47,   0.  ,  40.73,  36.78,
         40.33,  37.32,   0.  ,  34.85,  36.25,  39.82,   0.  ,  35.53,
         37.64,  45.52,  58.95,   0.  ,  41.35,  37.1 ,  37.35,  40.82,
         35.52,  42.24,  47.62,  42.78,   0.  ,  41.92,  44.76,  47.42,
         44.32,  45.25,  40.08,  41.96,  41.06,   0.  ,  39.53,  40.72,
         38.53,  38.42,  45.08,  41.58,  39.33,  40.4 ,   0.  ,  40.76,
         41.66,  45.54,  41.75,  36.74,  34.98,  32.55,  29.58,   0.  ,
         33.9 ,  34.32,  34.35,  28.06,   0.  ,  36.25,  31.33,  29.68,
         28.08,  32.47,  28.12,  28.45,  32.58,   0.  ,  32.22,  27.87,
         28.04,  26.7 ,  26.68,  27.18,  26.25,  28.48,   0.  ,  23.9 ,
         26.05,  27.94,  24.58,  33.02,  31.57,  29.2 ,  30.98,  34.56,
         35.8 ,  33.24,  31.45,  35.76,   0.  ,  40.11,  37.15,   0.  ,
         37.38,   0.  ,  42.23,  44.72,  44.24,   0.  ,  42.22,  43.96,
         45.05,  40.1 ,   0.  ,  41.33,  39.03,  40.5 ,  41.15,  43.33,
         48.23,  46.3 ,  43.14,   0.  ,  42.72,  43.42,  47.92,  46.96,
         48.98,  50.28,  48.9 ,  50.1 ,   0.  ,  53.18,  50.52,  51.56,
         52.3 ,  44.45,  40.12,  44.56,  48.33,   0.  ,  41.36,  42.82,
         41.56,  35.11,  39.6 ,  35.98,  36.  ,  33.78,   0.  ,  24.95,
         22.34,  24.48,  27.08,   0.  ,  24.02,  25.57,  26.24,  26.85,
         31.65,  32.17,  32.08,  33.48,   0.  ,  32.33,  36.48,  34.76,
         38.  ,  38.88,  42.53,  42.6 ,  42.17,   0.  ,  39.03,   0.  ,
         34.07,  33.47,   0.  ,  32.8 ,  35.25,  34.44,  33.95,  27.73,
         36.8 ,  35.74,  37.95,  37.  ,   0.  ,  37.88,  36.35,  39.56,
          0.  ,  41.66,  38.98,  36.84,  38.95,   0.  ,  37.57,  34.64,
         33.94,  36.52,   0.  ,  45.16,  42.16,  43.52,  44.32,  42.4 ,
         44.42,  45.52,  43.72,   0.  ,  43.8 ,  44.35,  43.2 ,  41.46,
         42.76,  41.61,  43.98,  43.55,   0.  ,  30.05,  32.23,  32.45,
         34.67,  31.2 ,  36.76,  38.95,  39.45,   0.  ,  38.33,  36.33,
         38.02,  38.65,  38.16,  38.03,  35.94,  33.04,   0.  ,  36.  ,
         35.86,  29.08,  28.33,  30.25,  30.1 ,  26.68,  26.28,   0.  ,
         29.02,  25.35,  23.77,  23.64,   0.  ,  26.8 ,  23.85,  24.7 ,
          0.  ,  29.12,  25.98,  24.83,  27.63,  27.07,   0.  ,  23.95,
         23.02,  21.33,  23.73,   0.  ,  23.76,   0.  ,  21.38,   0.  ,
         18.28,  22.27,   0.  ,  22.13,  21.23,  23.36,  22.96,  17.65,
         18.9 ,   0.  ,  21.32,  21.78,  15.12,  12.46,  16.04,  18.5 ,
         18.6 ,  16.3 ,   0.  ,  52.68,  52.05,  18.28,  20.  ,  17.92,
         17.19,  19.92,  21.38,   0.  ,  16.6 ,  15.52,  14.37,  15.6 ,
          0.  ,  14.68,  17.8 ,  15.84,   0.  ,  17.3 ,  17.75,  16.55,
         16.22,   0.  ,  12.48,  12.95,  14.67,  15.95,  16.87,  14.15,
         14.75,  15.3 ,   0.  ,  15.  ,  14.  ,  11.78,  14.13,  15.27,
         13.14,  14.26,  15.73,   0.  ,  16.33,  15.2 ,  15.27,  15.27,
         17.28,  16.2 ,  13.72,  13.  ,   0.  ,  14.65,  14.82,  15.14,
         13.24,  15.05,  15.68,  19.25,  17.  ,   0.  ,  16.38,  15.6 ,
         16.17,  14.94,  18.45,  16.88,  15.27,  15.62,   0.  ,  15.38,
          0.  ]),
 array([ 0.  ,  5.74,  3.29,  3.49,  4.14,  4.34,  3.47,  3.48,  4.64,
         4.54,  3.52,  4.84,  4.08,  3.  ,  0.  ,  4.84,  3.81,  5.42,
         7.14,  0.  ,  5.5 ,  4.73,  6.12,  7.66,  0.  ,  5.77,  6.52,
         5.27,  5.58,  4.97,  4.68,  4.7 ,  6.58,  0.  ,  5.18,  5.82,
         4.92,  4.16,  0.  ,  5.15,  4.07,  3.92,  4.7 ,  6.32,  5.7 ,
         4.73,  4.42,  3.85,  3.86,  3.98,  3.62,  4.1 ,  0.  ,  4.69,
         4.12,  4.1 ,  4.62,  0.  ,  5.65,  5.72,  5.75,  6.46,  6.04,
         5.44,  4.95,  5.24,  0.  ,  5.12,  4.75,  4.66,  5.68,  0.  ,
         4.48,  4.55,  4.95,  4.97,  0.  ,  5.7 ,  4.35,  4.58,  5.3 ,
         4.66,  4.14,  4.08,  4.62,  4.95,  4.6 ,  3.73,  4.23,  4.52,
         0.  ,  5.92,  6.32,  6.08,  6.92,  0.  , 10.4 , 11.37, 12.  ,
        10.92, 10.15,  8.6 ,  8.72, 11.17,  9.57,  9.92,  9.5 , 11.73,
        12.35, 13.54,  9.28, 11.7 , 12.35, 12.54,  0.  , 11.75, 14.24,
        14.05, 10.25,  0.  , 12.25, 13.93, 13.5 , 12.63,  0.  , 11.92,
        11.75,  9.16, 10.85, 11.24,  9.84,  9.65,  9.98,  0.  , 11.38,
        14.36, 14.85, 11.  ,  0.  ,  7.46,  7.66,  6.68,  7.25,  0.  ,
         6.58,  6.55,  5.74,  5.02,  0.  ,  5.04,  4.18,  5.55,  7.02,
         5.42,  5.94,  6.75,  5.96,  0.  ,  4.45,  5.1 ,  5.74,  6.92,
         0.  ,  6.84,  7.56,  8.98,  9.1 ,  8.88,  7.97,  6.17,  6.85,
         9.95,  8.14,  9.46, 12.06, 10.7 ,  0.  ,  9.1 ,  8.38,  9.02,
         9.17,  0.  ,  9.77, 12.32, 12.4 , 10.23, 10.77, 10.38,  9.41,
         9.82, 11.54, 14.9 , 13.9 , 15.3 , 14.42,  0.  , 17.53, 15.3 ,
        10.9 , 10.5 ,  0.  ,  9.64, 10.15, 14.22, 14.33, 11.15, 11.27,
        12.58, 13.6 , 14.93, 12.68, 14.32, 15.16, 15.  ,  0.  , 12.18,
        11.37, 10.97, 13.27,  0.  , 18.74, 19.47, 15.97, 15.89,  0.  ,
        17.52, 15.15, 15.78, 19.  , 15.39, 12.93, 13.2 , 17.25, 20.19,
        12.93, 11.86, 11.57, 11.32,  0.  , 14.11, 11.55, 11.4 , 13.7 ,
        14.08, 14.24, 12.62,  9.48, 11.52,  0.  , 16.15, 14.35, 12.35,
        13.95,  0.  , 12.3 , 10.8 ,  8.38,  8.37, 11.82, 12.75, 17.16,
        15.6 , 10.87, 15.92, 17.52, 15.05, 12.87,  0.  , 12.07, 13.12,
        14.34, 13.95,  0.  , 11.98, 11.16, 13.66, 14.42,  0.  , 11.27,
        13.47, 14.24, 12.02, 16.72, 13.93, 10.78, 13.3 ,  0.  , 13.61,
        11.4 , 13.32, 17.67,  0.  , 17.24, 15.18, 12.84, 14.45, 13.57,
        10.95,  8.05,  8.4 , 10.38, 12.25, 11.15, 10.04,  9.65,  0.  ,
         8.43,  7.94,  8.88,  9.45,  0.  , 10.4 ,  8.53,  8.13,  8.45,
         8.35,  6.58,  6.24,  7.58,  0.  ,  5.75,  6.77,  6.78,  4.42,
         0.  ,  7.07,  4.77,  3.07,  4.22,  0.  ,  5.95,  6.25,  5.01,
         3.85,  5.28,  6.28,  5.15,  3.54,  5.27,  4.8 ,  6.8 ,  7.36,
         5.12,  0.  ,  6.  ,  6.82,  4.58,  5.27,  0.  ,  6.92,  6.7 ,
         6.2 ,  6.33,  0.  ,  8.28,  9.59,  7.72,  5.16,  6.86,  6.7 ,
         6.5 ,  6.86,  0.  ,  6.28,  6.94,  7.44,  7.32,  0.  ,  7.82,
         8.  ,  9.05,  9.92,  0.  ,  7.02,  9.24,  9.5 ,  7.88,  9.34,
         8.54,  8.61,  8.8 ,  7.97,  0.  ,  4.7 , 10.7 ,  8.16,  6.  ,
         9.  ,  0.  , 11.13,  8.  ,  8.87,  8.82,  0.  , 10.88,  8.96,
         9.86,  9.36,  0.  ,  7.78,  8.3 ,  8.52,  8.6 ,  9.45,  8.3 ,
         7.72,  7.78,  8.45,  5.68,  6.15,  6.84,  6.32,  0.  ,  5.48,
         5.08,  5.48,  5.66,  0.  ,  6.56,  5.3 ,  5.06,  4.9 ,  3.6 ,
         4.78,  6.05,  4.72,  3.13,  4.04,  3.86,  2.6 ,  2.82,  0.  ,
         3.48,  1.86,  2.1 ,  2.72,  0.  ,  2.7 ,  1.98,  2.02,  2.5 ,
         0.  ,  2.22,  2.16,  1.34,  1.78,  0.  ,  2.08,  1.55,  1.4 ,
         1.15,  0.  ,  1.52,  1.38,  0.78,  1.1 ,  0.82,  1.15,  1.4 ,
         1.15,  1.24,  1.1 ,  1.25,  1.12,  0.88,  0.  ,  0.84,  1.57,
         1.55,  0.92,  0.  ,  1.3 ,  0.96,  1.1 ,  1.62,  0.  ,  1.3 ,
         1.45,  1.22,  0.88,  0.  ]),
 array([ 11.05,  10.84,  10.85,  11.3 ,  11.52,   0.  ,  10.85,  10.66,
         11.02,   9.1 ,   5.4 ,   7.1 ,   8.05,   5.7 ,   0.  ,   7.55,
          8.62,   7.48,   7.94,   0.  ,   7.98,   6.95,   6.02,   5.85,
          7.16,   6.16,   6.48,   6.04,   0.  ,   5.9 ,   5.03,   4.8 ,
          5.54,   4.72,   5.82,   5.66,   4.75,   5.55,   6.48,   7.12,
          7.56,   8.83,   9.14,   8.  ,  12.55,  10.92,   9.11,   9.64,
          0.  ,   7.82,   9.43,   9.38,   8.87,  11.92,  13.75,  13.98,
         13.64,  14.82,   0.  ,  23.76,  25.7 ,  21.95,  17.45,   0.  ,
         11.94,  11.02,  11.02,  11.58,  16.82,  20.47,  22.07,  24.62,
          0.  ,  21.14,  19.24,  14.82,  13.81,  19.13,  21.15,   0.  ,
         13.47,  13.72,   0.  ,  14.78,  13.6 ,  11.57,   0.  ,   0.  ,
         10.45,  11.83,  10.9 ,  10.39,  13.  ,  14.7 ,  14.74,  15.87,
         17.2 ,  18.98,  16.76,  16.26,  18.04,   0.  ,  21.04,  19.96,
         14.66,  11.62,  11.07,  13.2 ,  14.17,  12.24,   0.  ,  10.78,
         10.78,  10.88,  10.65,  10.92,  11.32,  13.33,  13.1 ,   0.  ,
         15.61,  14.38,  13.36,  13.  ,   0.  ,   8.82,   8.61,   8.41,
          9.  ,   9.82,   9.02,   8.92,   0.  ,   7.47,   0.  ,   0.  ,
          7.92,   8.45,   8.24,   7.76,  10.77,   9.88,   8.62,   8.1 ,
          0.  ,   8.47,   0.  ,  11.6 ,   8.78,   0.  ,   6.96,   8.88,
          9.6 ,   0.  ,   0.  ,   8.58,   9.73,  11.23,   9.62,   0.  ,
         10.98,  10.36,   9.35,  10.24,  11.62,  10.65,  11.14,  11.45,
          0.  ,  13.  ,  12.48,  11.65,  10.42,  10.78,  10.09,   9.42,
          9.65,   9.38,   0.  ,  10.28,  10.92,  10.2 ,   9.4 ,   0.  ,
         11.86,  11.76,  14.07,  13.62,  17.87,  17.58,  18.56,  20.12,
         21.15,   0.  ,  16.85,  14.02,  13.25,  11.85,  11.8 ,  11.97,
         12.15,  11.76,  12.52, 101.98,  37.07,  16.9 ,  17.  ,  21.05,
         47.76,  39.77,  38.7 ,  40.38,  36.98,   0.  ,  25.65,  25.57,
         17.73,   0.  ,  16.83,  10.72,   9.86,   7.46,   9.3 ,  11.42,
          0.  ,  10.84,  11.5 ,  10.26,   9.18,   7.64,   6.94,   8.65,
          9.05,   0.  ,  10.25,   9.08,   7.38,   8.37,   0.  ,   8.93,
          9.52,   8.18,   9.82,   0.  ,  10.55,  12.08,  10.68,  10.18,
          9.04,   8.72,   8.68,   6.95,   6.68,   0.  ,   8.38,   9.3 ,
          9.68,   0.  ,   9.82,   9.1 ,   0.  ,  11.17,  10.3 ,   0.  ,
          0.  ,  10.  ,   8.53,   7.46,   9.74,   9.13,   6.23,   9.02,
         10.16,   8.93,   0.  ,   8.05,   8.46,   7.8 ,   8.3 ,   7.78,
          7.24,   8.75,  11.65,   0.  ,   8.7 ,   9.18,  10.1 ,  10.28,
         10.72,  10.45,  10.72,  13.17,  13.14,  11.57,   0.  ,  11.73,
         11.63,  10.68,   8.72,   8.73,  10.12,  10.07,   8.32,   0.  ,
         10.57,  10.83,   0.  ,  10.43,   0.  ,  10.74,  11.74,   9.59,
          8.72,  10.83,   0.  ,   9.44,   9.28,   9.64,   9.32,   0.  ,
          9.93,  10.76,   9.18,   0.  ,   7.1 ,   0.  ,   6.02,   5.93,
          7.6 ,   9.14,   4.75,   4.54,   6.04,   6.36,   0.  ,   4.1 ,
          3.93,   3.95,   3.92,   0.  ,   3.36,   3.24,   3.57,   0.  ,
          3.34,   3.62,   3.64,   4.14,   0.  ,   4.18,   4.2 ,   3.05,
          2.74,   0.  ,   3.82,   2.96,   2.48,   2.48,   2.55,   2.5 ,
          2.9 ,   2.95,   0.  ,   2.45,   2.4 ,   2.56,   2.72,   2.58,
          2.66,   3.03,   2.86,   0.  ,   2.65,   2.4 ,   2.32,   2.35,
          0.  ,   2.34,   2.65,   2.66,   2.35,   2.27,   3.37,   2.87,
          2.27,   2.32,   2.3 ,   2.42,   2.55,   0.  ,   2.55,   0.  ,
          2.5 ,   2.92,   3.48,   3.  ,   2.46,   2.2 ,   0.  ,   2.4 ,
          2.3 ,   0.  ,   2.13,   3.07,   2.97,   2.6 ,   0.  ,   2.13,
          2.13,   2.18,   0.  ,   2.6 ,   2.45,   2.3 ,   2.15,   0.  ,
          2.06,   2.08,   2.04,   1.75,   1.72,   1.7 ,   1.76,   1.86,
          0.  ,   1.52,   1.7 ,   1.8 ,   1.58,   1.92,   2.88,   2.65,
          2.  ,   0.  ,   1.7 ,   1.7 ,   1.7 ,   1.64,   2.2 ,   1.86,
          1.86,   2.06,   2.16,   1.74,   0.  ,   2.45,   2.82,   2.78,
          2.58,   0.  ,   3.28,   3.16,   3.28,   3.42,   0.  ,   2.66,
          3.  ,   2.99,   3.2 ,   4.45,   6.08,   5.44,   5.35,   0.  ,
          3.75,   3.96,   3.23,   2.58,   3.84,   4.43,   0.  ,   4.23,
          4.75,   4.47,   4.57,   0.  ,   5.95,   7.62,   9.75,   8.86,
          0.  ]),
 array([ 1.78,  2.26,  3.15,  2.72,  3.3 ,  1.7 ,  1.75,  0.  ,  2.72,
         2.82,  2.54,  2.26,  0.  ,  1.58,  1.8 ,  2.08,  1.78,  0.  ,
         2.08,  1.9 ,  2.82,  4.16,  1.7 ,  1.65,  1.87,  2.23,  0.  ,
         1.9 ,  1.44,  1.95,  2.08,  0.  ,  1.72,  1.28,  1.27,  1.38,
         2.57,  4.  ,  3.63,  3.88,  0.  ,  2.05,  2.49,  3.14,  2.11,
         0.  ,  2.7 ,  2.92,  3.22,  2.46,  0.  ,  2.34,  1.21,  1.53,
         2.38,  0.95,  1.67,  2.24,  3.05,  2.35,  1.25,  2.35,  2.15,
         2.18,  0.  ,  1.22,  1.44,  2.22,  2.22,  0.  ,  0.64,  1.44,
         3.78,  4.15,  1.82,  1.86,  2.7 ,  3.38,  0.  ,  2.  ,  2.66,
         2.16,  1.53,  0.  ,  2.16,  2.13,  2.55,  1.6 ,  2.35,  2.04,
         2.52,  3.07,  2.95,  2.28,  2.1 ,  2.  ,  3.08,  0.  ,  1.95,
         2.86,  3.38,  3.51,  0.  ,  4.95,  3.14,  3.02,  2.4 ,  1.55,
         1.42,  1.68,  1.92,  0.  ,  2.82,  2.66,  2.4 ,  2.35,  0.  ,
         2.4 ,  1.98,  2.44,  2.42,  1.35,  1.36,  3.14,  3.2 ,  1.8 ,
         3.  ,  2.17,  2.04,  1.56,  0.  ,  2.04,  2.2 ,  1.48,  1.6 ,
         0.  ,  1.42,  1.3 ,  1.3 ,  1.15,  1.14,  2.15,  2.05,  1.32,
         1.06,  0.68,  0.8 ,  0.73,  0.56,  0.  ,  2.01,  2.06,  1.92,
         2.15,  0.  ,  1.48,  1.72,  1.74,  2.04,  4.65,  5.15,  4.65,
         5.66,  0.  ,  4.28,  4.52,  4.46,  6.32,  0.  ,  5.53,  7.62,
         7.56,  7.13,  5.2 ,  7.95,  7.72,  5.58,  5.62,  6.33,  5.46,
         5.24,  5.98,  0.  ,  7.06,  7.56,  5.4 ,  8.34,  0.  ,  5.27,
         4.2 ,  6.25,  7.55,  5.1 ,  5.22,  5.16,  5.23,  0.  ,  8.92,
         8.38,  7.04,  6.94,  0.  ,  7.83,  8.3 ,  8.8 ,  7.9 ,  8.78,
         8.12,  7.85,  6.3 ,  7.06,  5.55,  5.82,  8.56, 11.84,  0.  ,
         7.46,  7.42,  9.12,  7.76,  0.  ,  8.72, 40.22,  0.  , 18.62,
        10.72, 11.45, 13.37, 13.4 , 12.42,  9.91,  8.36,  9.06, 10.11,
         0.  ,  8.74,  9.28,  8.9 ,  9.14,  0.  ,  9.8 , 10.73,  9.43,
         9.78,  0.  ,  7.53,  8.45, 10.84, 11.84,  9.63, 12.02, 11.75,
        12.82,  0.  , 18.36, 19.78, 11.35, 10.7 ,  0.  , 12.43, 13.12,
        11.18,  9.55, 10.02, 11.35, 11.87, 11.17,  0.  , 11.57,  9.78,
         9.83, 15.3 ,  0.  , 11.1 , 11.08, 14.14, 14.62,  0.  , 13.98,
        12.36, 12.28, 13.23, 12.56, 12.05,  9.36,  9.2 ,  0.  , 11.7 ,
        10.42,  9.95,  9.46,  0.  , 12.05, 10.82, 10.26, 12.28, 15.97,
        13.85,  0.  , 14.83, 12.16,  0.  , 13.22, 14.02, 12.08, 12.25,
         9.25, 11.8 , 12.02, 11.94, 14.36, 10.42, 10.23, 12.18, 12.42,
         0.  , 10.76, 10.82, 11.4 , 11.3 ,  0.  ,  9.14,  8.57,  9.18,
        10.38,  8.26,  8.76,  8.59,  7.48,  0.  , 10.4 , 10.67,  9.43,
        10.36,  0.  ,  8.12,  9.55,  6.78,  7.56,  6.7 ,  6.08,  9.12,
        10.32,  8.36,  5.68,  7.22,  8.76,  8.06,  0.  ,  7.13,  5.82,
         7.48,  6.07,  0.  ,  6.25,  6.58,  8.34,  8.15,  6.65,  6.28,
         7.2 ,  7.72,  0.  ,  5.36,  3.25,  4.7 ,  6.68,  0.  ,  8.  ,
         9.38,  7.13,  5.65,  5.26,  5.75,  5.77,  5.14,  4.46,  5.46,
         4.33,  4.92,  5.06,  7.67,  0.  ,  3.33,  3.33,  5.36,  7.95,
         6.76,  0.  ,  5.39,  6.56,  5.86,  5.4 ,  0.  ,  6.55,  6.58,