# Luftdaten data : data cleaning, resampling
## Code builds a continuous time tabular version of the luftdaen data, such that the same time period is present for each sensor in the data, regardless of whether each sensor has data for all the time slots. 

## The slot-filling is done to make it easier to use the data.

In [2]:
import pandas as pd
import numpy as np
import time

In [3]:
one = pd.Timestamp( time.ctime() )

In [4]:
one

Timestamp('2019-01-18 09:38:17')

In [5]:
dir( time )

['_STRUCT_TM_ITEMS',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'altzone',
 'asctime',
 'clock',
 'ctime',
 'daylight',
 'get_clock_info',
 'gmtime',
 'localtime',
 'mktime',
 'monotonic',
 'perf_counter',
 'process_time',
 'sleep',
 'strftime',
 'strptime',
 'struct_time',
 'time',
 'timezone',
 'tzname',
 'tzset']

In [6]:
time.ctime()

'Fri Jan 18 09:38:17 2019'

In [7]:

pd.Timedelta( '1 days')

Timedelta('1 days 00:00:00')

In [8]:
pd.Timedelta( days=1, seconds=1 )

Timedelta('1 days 00:00:01')

In [9]:
pd.Timedelta( np.timedelta64( 1, 'ms'))

Timedelta('0 days 00:00:00.001000')

In [10]:
daterange = pd.date_range( time.ctime(), periods=24, freq='H')

In [11]:
daterange

DatetimeIndex(['2019-01-18 09:38:17', '2019-01-18 10:38:17',
               '2019-01-18 11:38:17', '2019-01-18 12:38:17',
               '2019-01-18 13:38:17', '2019-01-18 14:38:17',
               '2019-01-18 15:38:17', '2019-01-18 16:38:17',
               '2019-01-18 17:38:17', '2019-01-18 18:38:17',
               '2019-01-18 19:38:17', '2019-01-18 20:38:17',
               '2019-01-18 21:38:17', '2019-01-18 22:38:17',
               '2019-01-18 23:38:17', '2019-01-19 00:38:17',
               '2019-01-19 01:38:17', '2019-01-19 02:38:17',
               '2019-01-19 03:38:17', '2019-01-19 04:38:17',
               '2019-01-19 05:38:17', '2019-01-19 06:38:17',
               '2019-01-19 07:38:17', '2019-01-19 08:38:17'],
              dtype='datetime64[ns]', freq='H')

In [12]:
# move back one day… 
daterange - pd.Timedelta( days=1 )

DatetimeIndex(['2019-01-17 09:38:17', '2019-01-17 10:38:17',
               '2019-01-17 11:38:17', '2019-01-17 12:38:17',
               '2019-01-17 13:38:17', '2019-01-17 14:38:17',
               '2019-01-17 15:38:17', '2019-01-17 16:38:17',
               '2019-01-17 17:38:17', '2019-01-17 18:38:17',
               '2019-01-17 19:38:17', '2019-01-17 20:38:17',
               '2019-01-17 21:38:17', '2019-01-17 22:38:17',
               '2019-01-17 23:38:17', '2019-01-18 00:38:17',
               '2019-01-18 01:38:17', '2019-01-18 02:38:17',
               '2019-01-18 03:38:17', '2019-01-18 04:38:17',
               '2019-01-18 05:38:17', '2019-01-18 06:38:17',
               '2019-01-18 07:38:17', '2019-01-18 08:38:17'],
              dtype='datetime64[ns]', freq='H')

In [13]:
# move back a dew hours… 
daterange - pd.Timedelta( hours=1 )

DatetimeIndex(['2019-01-18 08:38:17', '2019-01-18 09:38:17',
               '2019-01-18 10:38:17', '2019-01-18 11:38:17',
               '2019-01-18 12:38:17', '2019-01-18 13:38:17',
               '2019-01-18 14:38:17', '2019-01-18 15:38:17',
               '2019-01-18 16:38:17', '2019-01-18 17:38:17',
               '2019-01-18 18:38:17', '2019-01-18 19:38:17',
               '2019-01-18 20:38:17', '2019-01-18 21:38:17',
               '2019-01-18 22:38:17', '2019-01-18 23:38:17',
               '2019-01-19 00:38:17', '2019-01-19 01:38:17',
               '2019-01-19 02:38:17', '2019-01-19 03:38:17',
               '2019-01-19 04:38:17', '2019-01-19 05:38:17',
               '2019-01-19 06:38:17', '2019-01-19 07:38:17'],
              dtype='datetime64[ns]', freq='H')

In [14]:
# try make a time range, back in time, based on variables
hours_ = 24

In [15]:
original_time_range = pd.date_range( time.ctime(), periods=hours_, freq="H")
original_time_range

DatetimeIndex(['2019-01-18 09:38:17', '2019-01-18 10:38:17',
               '2019-01-18 11:38:17', '2019-01-18 12:38:17',
               '2019-01-18 13:38:17', '2019-01-18 14:38:17',
               '2019-01-18 15:38:17', '2019-01-18 16:38:17',
               '2019-01-18 17:38:17', '2019-01-18 18:38:17',
               '2019-01-18 19:38:17', '2019-01-18 20:38:17',
               '2019-01-18 21:38:17', '2019-01-18 22:38:17',
               '2019-01-18 23:38:17', '2019-01-19 00:38:17',
               '2019-01-19 01:38:17', '2019-01-19 02:38:17',
               '2019-01-19 03:38:17', '2019-01-19 04:38:17',
               '2019-01-19 05:38:17', '2019-01-19 06:38:17',
               '2019-01-19 07:38:17', '2019-01-19 08:38:17'],
              dtype='datetime64[ns]', freq='H')

In [16]:
date_range_moved = original_time_range - pd.Timedelta( hours=hours_ ) 
date_range_moved

DatetimeIndex(['2019-01-17 09:38:17', '2019-01-17 10:38:17',
               '2019-01-17 11:38:17', '2019-01-17 12:38:17',
               '2019-01-17 13:38:17', '2019-01-17 14:38:17',
               '2019-01-17 15:38:17', '2019-01-17 16:38:17',
               '2019-01-17 17:38:17', '2019-01-17 18:38:17',
               '2019-01-17 19:38:17', '2019-01-17 20:38:17',
               '2019-01-17 21:38:17', '2019-01-17 22:38:17',
               '2019-01-17 23:38:17', '2019-01-18 00:38:17',
               '2019-01-18 01:38:17', '2019-01-18 02:38:17',
               '2019-01-18 03:38:17', '2019-01-18 04:38:17',
               '2019-01-18 05:38:17', '2019-01-18 06:38:17',
               '2019-01-18 07:38:17', '2019-01-18 08:38:17'],
              dtype='datetime64[ns]', freq='H')

In [17]:
date_range_moved_as_epoc = date_range_moved.astype( np.int32 )
date_range_moved_as_epoc

Int64Index([1547717897000000000, 1547721497000000000, 1547725097000000000,
            1547728697000000000, 1547732297000000000, 1547735897000000000,
            1547739497000000000, 1547743097000000000, 1547746697000000000,
            1547750297000000000, 1547753897000000000, 1547757497000000000,
            1547761097000000000, 1547764697000000000, 1547768297000000000,
            1547771897000000000, 1547775497000000000, 1547779097000000000,
            1547782697000000000, 1547786297000000000, 1547789897000000000,
            1547793497000000000, 1547797097000000000, 1547800697000000000],
           dtype='int64')

In [18]:
date_range_moved.shape

(24,)

In [19]:
date_range_moved[0]

Timestamp('2019-01-17 09:38:17', freq='H')

In [20]:
dir( date_range_moved[0] )

['__add__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__pyx_vtable__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__weakref__',
 '_date_attributes',
 '_date_repr',
 '_get_date_name_field',
 '_get_start_end_field',
 '_has_time_component',
 '_repr_base',
 '_round',
 '_short_repr',
 '_time_repr',
 'asm8',
 'astimezone',
 'ceil',
 'combine',
 'ctime',
 'date',
 'day',
 'day_name',
 'dayofweek',
 'dayofyear',
 'days_in_month',
 'daysinmonth',
 'dst',
 'floor',
 'fold',
 'freq',
 'freqstr',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'is_leap_year',
 'is_month_end',
 'is_month_start',
 'is_quarter_end',
 'is_quarter_start',
 'is_year_end',
 'is_year_start',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'microsecond',
 'min',
 'minute',
 'month',
 'month_name',
 'nanosecond',
 'normalize',
 'now',
 'quarter',
 'replace',
 'resolution',
 'round',
 'second',
 'strftime',
 'strptime',
 'time',
 'timestamp',
 'timetuple',
 'timetz',
 'to_datetime64',
 'to_julian_date',
 'to_period',
 'to_pydatetime',
 'today',
 'toordinal',
 'tz',
 'tz_convert',
 'tz_localize',
 'tzinfo',
 'tzname',
 'utcfromtimestamp',
 'utcnow',
 'utcoffset',
 'utctimetuple',
 'value',
 'week',
 'weekday',
 'weekday_name',
 'weekofyear',
 'year']

In [21]:
 date_range_moved[0].ctime()

'Thu Jan 17 09:38:17 2019'

In [22]:
 date_range_moved[0].timestamp()

1547717897.0

In [23]:
str( date_range_moved[0] )

'2019-01-17 09:38:17'

In [24]:
start_time = time.time()
start_time

time.sleep( 1 )
time_1_sec_later = time.time()

In [25]:
time_diff = time_1_sec_later - start_time
time_diff

1.001819133758545

In [26]:
# another go with getting the right time range
# - we start with the time range
daterange2 = pd.date_range( time.ctime(), periods=24, freq='H')
daterange2

DatetimeIndex(['2019-01-18 09:38:19', '2019-01-18 10:38:19',
               '2019-01-18 11:38:19', '2019-01-18 12:38:19',
               '2019-01-18 13:38:19', '2019-01-18 14:38:19',
               '2019-01-18 15:38:19', '2019-01-18 16:38:19',
               '2019-01-18 17:38:19', '2019-01-18 18:38:19',
               '2019-01-18 19:38:19', '2019-01-18 20:38:19',
               '2019-01-18 21:38:19', '2019-01-18 22:38:19',
               '2019-01-18 23:38:19', '2019-01-19 00:38:19',
               '2019-01-19 01:38:19', '2019-01-19 02:38:19',
               '2019-01-19 03:38:19', '2019-01-19 04:38:19',
               '2019-01-19 05:38:19', '2019-01-19 06:38:19',
               '2019-01-19 07:38:19', '2019-01-19 08:38:19'],
              dtype='datetime64[ns]', freq='H')

In [27]:
# we subtract the period frequency we originally set
daterange_minus_24_hours = daterange2 - 24
daterange_minus_24_hours

DatetimeIndex(['2019-01-17 09:38:19', '2019-01-17 10:38:19',
               '2019-01-17 11:38:19', '2019-01-17 12:38:19',
               '2019-01-17 13:38:19', '2019-01-17 14:38:19',
               '2019-01-17 15:38:19', '2019-01-17 16:38:19',
               '2019-01-17 17:38:19', '2019-01-17 18:38:19',
               '2019-01-17 19:38:19', '2019-01-17 20:38:19',
               '2019-01-17 21:38:19', '2019-01-17 22:38:19',
               '2019-01-17 23:38:19', '2019-01-18 00:38:19',
               '2019-01-18 01:38:19', '2019-01-18 02:38:19',
               '2019-01-18 03:38:19', '2019-01-18 04:38:19',
               '2019-01-18 05:38:19', '2019-01-18 06:38:19',
               '2019-01-18 07:38:19', '2019-01-18 08:38:19'],
              dtype='datetime64[ns]', freq='H')

In [28]:
# and then, just for practice, turn it into epoch 
daterange_minus_24_hours__as_epoc = daterange_minus_24_hours.astype( np.int32 )
daterange_minus_24_hours__as_epoc

Int64Index([1547717899000000000, 1547721499000000000, 1547725099000000000,
            1547728699000000000, 1547732299000000000, 1547735899000000000,
            1547739499000000000, 1547743099000000000, 1547746699000000000,
            1547750299000000000, 1547753899000000000, 1547757499000000000,
            1547761099000000000, 1547764699000000000, 1547768299000000000,
            1547771899000000000, 1547775499000000000, 1547779099000000000,
            1547782699000000000, 1547786299000000000, 1547789899000000000,
            1547793499000000000, 1547797099000000000, 1547800699000000000],
           dtype='int64')

In [29]:
type( daterange_minus_24_hours__as_epoc[0] )

numpy.int64

In [30]:
single_daterange_as_epoch__value = daterange_minus_24_hours__as_epoc[0]

In [31]:
# try convert the timestamp in the data, to epoch

in_data = pd.read_csv( "/Users/miska/Documents/open_something/luftdaten/luftdaten_code/luftdaten__make_tabular_data__from_db_data/ld_NYE_midnight_24hrs_nordics_all_data_01.csv" )

In [32]:
in_data.dtypes

sensor_id         int64
sensor_namee     object
lat             float64
lon             float64
timestamp        object
p1              float64
p2              float64
dtype: object

In [33]:
in_data['timestamp'] = pd.to_datetime( in_data['timestamp'] )

In [34]:
in_data.dtypes

sensor_id                int64
sensor_namee            object
lat                    float64
lon                    float64
timestamp       datetime64[ns]
p1                     float64
p2                     float64
dtype: object

In [35]:
in_data

,sensor_id,sensor_namee,lat,lon,timestamp,p1,p2
0,7273,SDS011,60.002,17.846,2018-12-31 11:57:22,3.43,1.56
1,7275,SDS011,57.720,11.888,2018-12-31 11:58:44,482.77,33.82
2,7277,SDS011,59.266,15.230,2018-12-31 11:58:47,5.48,2.47
3,7406,SDS011,56.964,24.128,2018-12-31 11:56:41,11.05,6.62
4,7428,SDS011,59.868,17.624,2018-12-31 11:57:42,1.78,1.02
5,7469,SDS011,56.944,24.142,2018-12-31 11:57:52,8.40,5.54
6,7597,SDS011,59.320,18.064,2018-12-31 11:58:51,3.68,2.00
7,8683,SDS011,59.744,18.206,2018-12-31 11:58:28,3.01,2.80
8,9411,SDS011,59.266,15.230,2018-12-31 11:57:18,3.44,2.18
9,9436,SDS011,59.334,18.034,2018-12-31 11:57:22,2.12,1.90
10,9743,SDS011,57.664,12.054,2018-12-31 11:57:15,268.58,29.05
11,9797,SDS011,57.492,12.652,2018-12-31 11:58:52,10.13,7.05
12,10216,SDS011,59.674,16.838,2018-12-31 11:57:28,3.94,2.75
13,10250,SDS011,58.692,12.478,2018-12-31 11:58:38,11.55,5.88
14,10281,SDS011,59.472,18.048,2018-12-31 11:58:42,5.18,3.12
15,10430,SDS011,59.958,17.726,2018-12-31 11:57:35,2.42,1.58
16,10647,SDS011,55.608,13.036,2018-12-31 11:58:28,14.65,5.10
17,10721,SDS011,59.450,18.124,2018-12-31 11:57:54,2.28,1.45
18,10723,SDS011,59.298,18.052,2018-12-31 11:56:45,4.90,2.76
19,10803,SDS011,57.690,11.954,2018-12-31 11:58:07,31.01,6.02
20,10823,SDS011,59.332,18.034,2018-12-31 11:57:37,3.78,2.05
21,10825,SDS011,55.898,14.094,2018-12-31 11:57:55,9.50,7.00
22,10827,SDS011,59.334,13.512,2018-12-31 11:56:40,11.45,6.00
23,10843,SDS011,59.354,18.364,2018-12-31 11:58:46,5.44,2.13
24,10914,SDS011,61.450,23.858,2018-12-31 11:58:48,1.97,1.88
25,10922,SDS011,59.494,17.976,2018-12-31 11:57:26,5.75,3.05
26,10924,SDS011,59.860,17.652,2018-12-31 11:56:44,2.58,1.16
27,10926,SDS011,59.472,18.304,2018-12-31 11:57:06,3.26,2.35
28,11002,SDS011,55.796,13.090,2018-12-31 11:58:37,6.34,3.08
29,11004,SDS011,59.622,16.556,2018-12-31 11:58:53,4.40,1.95
...,...,...,...,...,...,...,...
127079,18826,SDS011,63.404,13.016,2019-01-01 11:59:35,11.82,1.67
127080,18836,SDS011,63.404,13.030,2019-01-01 11:59:39,12.26,1.97
127081,19119,SDS011,56.972,24.132,2019-01-01 11:56:33,10.84,3.66
127082,19207,SDS011,59.466,18.036,2019-01-01 11:58:20,5.74,2.40
127083,19301,SDS011,59.362,12.152,2019-01-01 11:56:50,0.02,0.00
127084,7273,SDS011,60.002,17.846,2019-01-01 11:59:34,2.63,1.30
127085,11232,SDS011,55.596,13.022,2019-01-01 11:59:46,16.80,4.07
127086,11374,SDS011,59.258,18.008,2019-01-01 11:59:40,6.35,4.08
127087,11378,SDS011,59.392,16.748,2019-01-01 11:59:47,1.25,0.64
127088,11445,SDS011,64.178,15.432,2019-01-01 11:59:51,0.45,0.26
127089,11546,SDS011,59.456,17.802,2019-01-01 11:59:45,1.42,0.86
127090,11663,SDS011,59.380,18.040,2019-01-01 11:59:48,1.77,1.10
127091,11769,SDS011,59.238,18.226,2019-01-01 11:59:56,2.49,1.35
127092,12383,SDS011,63.808,20.336,2019-01-01 11:59:40,2.13,0.65
127093,12387,SDS011,58.560,15.306,2019-01-01 11:59:52,1.10,0.65
127094,12673,SDS011,59.364,18.022,2019-01-01 11:59:49,2.63,1.50
127095,12675,SDS011,59.450,17.892,2019-01-01 11:59:47,3.30,1.52
127096,12691,SDS011,57.636,18.304,2019-01-01 11:59:55,5.25,1.94
127097,12990,SDS011,57.692,11.958,2019-01-01 11:58:00,16.63,3.60
127098,13012,SDS011,57.662,12.006,2019-01-01 11:59:58,8.18,2.25
127099,13020,SDS011,57.722,11.948,2019-01-01 11:59:41,20.64,3.67
127100,16147,SDS011,59.364,18.018,2019-01-01 11:59:46,3.28,1.80
127101,16153,SDS011,55.648,13.208,2019-01-01 11:57:19,20.00,3.90
127102,16296,SDS011,56.144,13.394,2019-01-01 11:59:59,23.86,7.45
127103,16533,SDS011,55.722,13.202,2019-01-01 11:56:55,18.05,4.33
127104,16723,SDS011,57.736,11.894,2019-01-01 11:58:57,16.47,3.40
127105,16815,SDS011,59.462,18.040,2019-01-01 11:59:36,2.67,1.97
127106,17235,SDS011,59.272,17.780,2019-01-01 11:59:41,4.69,1.82
127107,10588,SDS011,55.676,13.346,2019-01-01 11:57:12,14.08,3.68
127108,10647,SDS011,55.608,13.036,2019-01-01 11:58:42,23.42,4.75

In [36]:
in_data_as_epoch = in_data
in_data_as_epoch['timestamp'] = in_data_as_epoch['timestamp'].astype( 'int64' )
in_data_as_epoch

,sensor_id,sensor_namee,lat,lon,timestamp,p1,p2
0,7273,SDS011,60.002,17.846,1546257442000000000,3.43,1.56
1,7275,SDS011,57.720,11.888,1546257524000000000,482.77,33.82
2,7277,SDS011,59.266,15.230,1546257527000000000,5.48,2.47
3,7406,SDS011,56.964,24.128,1546257401000000000,11.05,6.62
4,7428,SDS011,59.868,17.624,1546257462000000000,1.78,1.02
5,7469,SDS011,56.944,24.142,1546257472000000000,8.40,5.54
6,7597,SDS011,59.320,18.064,1546257531000000000,3.68,2.00
7,8683,SDS011,59.744,18.206,1546257508000000000,3.01,2.80
8,9411,SDS011,59.266,15.230,1546257438000000000,3.44,2.18
9,9436,SDS011,59.334,18.034,1546257442000000000,2.12,1.90
10,9743,SDS011,57.664,12.054,1546257435000000000,268.58,29.05
11,9797,SDS011,57.492,12.652,1546257532000000000,10.13,7.05
12,10216,SDS011,59.674,16.838,1546257448000000000,3.94,2.75
13,10250,SDS011,58.692,12.478,1546257518000000000,11.55,5.88
14,10281,SDS011,59.472,18.048,1546257522000000000,5.18,3.12
15,10430,SDS011,59.958,17.726,1546257455000000000,2.42,1.58
16,10647,SDS011,55.608,13.036,1546257508000000000,14.65,5.10
17,10721,SDS011,59.450,18.124,1546257474000000000,2.28,1.45
18,10723,SDS011,59.298,18.052,1546257405000000000,4.90,2.76
19,10803,SDS011,57.690,11.954,1546257487000000000,31.01,6.02
20,10823,SDS011,59.332,18.034,1546257457000000000,3.78,2.05
21,10825,SDS011,55.898,14.094,1546257475000000000,9.50,7.00
22,10827,SDS011,59.334,13.512,1546257400000000000,11.45,6.00
23,10843,SDS011,59.354,18.364,1546257526000000000,5.44,2.13
24,10914,SDS011,61.450,23.858,1546257528000000000,1.97,1.88
25,10922,SDS011,59.494,17.976,1546257446000000000,5.75,3.05
26,10924,SDS011,59.860,17.652,1546257404000000000,2.58,1.16
27,10926,SDS011,59.472,18.304,1546257426000000000,3.26,2.35
28,11002,SDS011,55.796,13.090,1546257517000000000,6.34,3.08
29,11004,SDS011,59.622,16.556,1546257533000000000,4.40,1.95
...,...,...,...,...,...,...,...
127079,18826,SDS011,63.404,13.016,1546343975000000000,11.82,1.67
127080,18836,SDS011,63.404,13.030,1546343979000000000,12.26,1.97
127081,19119,SDS011,56.972,24.132,1546343793000000000,10.84,3.66
127082,19207,SDS011,59.466,18.036,1546343900000000000,5.74,2.40
127083,19301,SDS011,59.362,12.152,1546343810000000000,0.02,0.00
127084,7273,SDS011,60.002,17.846,1546343974000000000,2.63,1.30
127085,11232,SDS011,55.596,13.022,1546343986000000000,16.80,4.07
127086,11374,SDS011,59.258,18.008,1546343980000000000,6.35,4.08
127087,11378,SDS011,59.392,16.748,1546343987000000000,1.25,0.64
127088,11445,SDS011,64.178,15.432,1546343991000000000,0.45,0.26
127089,11546,SDS011,59.456,17.802,1546343985000000000,1.42,0.86
127090,11663,SDS011,59.380,18.040,1546343988000000000,1.77,1.10
127091,11769,SDS011,59.238,18.226,1546343996000000000,2.49,1.35
127092,12383,SDS011,63.808,20.336,1546343980000000000,2.13,0.65
127093,12387,SDS011,58.560,15.306,1546343992000000000,1.10,0.65
127094,12673,SDS011,59.364,18.022,1546343989000000000,2.63,1.50
127095,12675,SDS011,59.450,17.892,1546343987000000000,3.30,1.52
127096,12691,SDS011,57.636,18.304,1546343995000000000,5.25,1.94
127097,12990,SDS011,57.692,11.958,1546343880000000000,16.63,3.60
127098,13012,SDS011,57.662,12.006,1546343998000000000,8.18,2.25
127099,13020,SDS011,57.722,11.948,1546343981000000000,20.64,3.67
127100,16147,SDS011,59.364,18.018,1546343986000000000,3.28,1.80
127101,16153,SDS011,55.648,13.208,1546343839000000000,20.00,3.90
127102,16296,SDS011,56.144,13.394,1546343999000000000,23.86,7.45
127103,16533,SDS011,55.722,13.202,1546343815000000000,18.05,4.33
127104,16723,SDS011,57.736,11.894,1546343937000000000,16.47,3.40
127105,16815,SDS011,59.462,18.040,1546343976000000000,2.67,1.97
127106,17235,SDS011,59.272,17.780,1546343981000000000,4.69,1.82
127107,10588,SDS011,55.676,13.346,1546343832000000000,14.08,3.68
127108,10647,SDS011,55.608,13.036,1546343922000000000,23.42,4.75

In [37]:
type( in_data_as_epoch['timestamp'][0] )

numpy.int64

In [38]:
single_timestamp_value_as_epoch__value = in_data_as_epoch['timestamp'][0]

In [39]:
# both values 
single_daterange_as_epoch__value, single_timestamp_value_as_epoch__value

(1547717899000000000, 1546257442000000000)

In [40]:
( single_timestamp_value_as_epoch__value - single_daterange_as_epoch__value ) / ( 60*60*24 * 1000000000
                                                                                )

-16.9034375

In [41]:
len( str( single_daterange_as_epoch__value )), len( str( single_timestamp_value_as_epoch__value ))

(19, 19)

In [42]:
# divide by a billion to get the time value in seconds ; ) 
time.ctime( single_daterange_as_epoch__value/1000000000 )

'Thu Jan 17 10:38:19 2019'

In [43]:
# dry run

In [44]:
start_time = "2018-12-31 11:58:42"
end_time = "2019-01-01 11:58:42"

In [45]:
# set up the relevant time range

In [46]:
time_frequency = "5T"
num_of_time_periods = 24*12+1

In [47]:
time_date_range = pd.date_range( end_time, periods=num_of_time_periods, freq = time_frequency ) 
time_date_range = time_date_range - ( num_of_time_periods -1 )
time_date_range

DatetimeIndex(['2018-12-31 11:58:42', '2018-12-31 12:03:42',
               '2018-12-31 12:08:42', '2018-12-31 12:13:42',
               '2018-12-31 12:18:42', '2018-12-31 12:23:42',
               '2018-12-31 12:28:42', '2018-12-31 12:33:42',
               '2018-12-31 12:38:42', '2018-12-31 12:43:42',
               ...
               '2019-01-01 11:13:42', '2019-01-01 11:18:42',
               '2019-01-01 11:23:42', '2019-01-01 11:28:42',
               '2019-01-01 11:33:42', '2019-01-01 11:38:42',
               '2019-01-01 11:43:42', '2019-01-01 11:48:42',
               '2019-01-01 11:53:42', '2019-01-01 11:58:42'],
              dtype='datetime64[ns]', length=289, freq='5T')

In [48]:
time_date_range_as_epoch = time_date_range.astype( np.int64 )
time_date_range_as_epoch

Int64Index([1546257522000000000, 1546257822000000000, 1546258122000000000,
            1546258422000000000, 1546258722000000000, 1546259022000000000,
            1546259322000000000, 1546259622000000000, 1546259922000000000,
            1546260222000000000,
            ...
            1546341222000000000, 1546341522000000000, 1546341822000000000,
            1546342122000000000, 1546342422000000000, 1546342722000000000,
            1546343022000000000, 1546343322000000000, 1546343622000000000,
            1546343922000000000],
           dtype='int64', length=289)

In [51]:
type( time_date_range_as_epoch[0]

numpy.int64

In [48]:
# work with the in data 
in_data

,sensor_id,sensor_namee,lat,lon,timestamp,p1,p2
0,7273,SDS011,60.002,17.846,1546257442000000000,3.43,1.56
1,7275,SDS011,57.720,11.888,1546257524000000000,482.77,33.82
2,7277,SDS011,59.266,15.230,1546257527000000000,5.48,2.47
3,7406,SDS011,56.964,24.128,1546257401000000000,11.05,6.62
4,7428,SDS011,59.868,17.624,1546257462000000000,1.78,1.02
5,7469,SDS011,56.944,24.142,1546257472000000000,8.40,5.54
6,7597,SDS011,59.320,18.064,1546257531000000000,3.68,2.00
7,8683,SDS011,59.744,18.206,1546257508000000000,3.01,2.80
8,9411,SDS011,59.266,15.230,1546257438000000000,3.44,2.18
9,9436,SDS011,59.334,18.034,1546257442000000000,2.12,1.90
10,9743,SDS011,57.664,12.054,1546257435000000000,268.58,29.05
11,9797,SDS011,57.492,12.652,1546257532000000000,10.13,7.05
12,10216,SDS011,59.674,16.838,1546257448000000000,3.94,2.75
13,10250,SDS011,58.692,12.478,1546257518000000000,11.55,5.88
14,10281,SDS011,59.472,18.048,1546257522000000000,5.18,3.12
15,10430,SDS011,59.958,17.726,1546257455000000000,2.42,1.58
16,10647,SDS011,55.608,13.036,1546257508000000000,14.65,5.10
17,10721,SDS011,59.450,18.124,1546257474000000000,2.28,1.45
18,10723,SDS011,59.298,18.052,1546257405000000000,4.90,2.76
19,10803,SDS011,57.690,11.954,1546257487000000000,31.01,6.02
20,10823,SDS011,59.332,18.034,1546257457000000000,3.78,2.05
21,10825,SDS011,55.898,14.094,1546257475000000000,9.50,7.00
22,10827,SDS011,59.334,13.512,1546257400000000000,11.45,6.00
23,10843,SDS011,59.354,18.364,1546257526000000000,5.44,2.13
24,10914,SDS011,61.450,23.858,1546257528000000000,1.97,1.88
25,10922,SDS011,59.494,17.976,1546257446000000000,5.75,3.05
26,10924,SDS011,59.860,17.652,1546257404000000000,2.58,1.16
27,10926,SDS011,59.472,18.304,1546257426000000000,3.26,2.35
28,11002,SDS011,55.796,13.090,1546257517000000000,6.34,3.08
29,11004,SDS011,59.622,16.556,1546257533000000000,4.40,1.95
...,...,...,...,...,...,...,...
127079,18826,SDS011,63.404,13.016,1546343975000000000,11.82,1.67
127080,18836,SDS011,63.404,13.030,1546343979000000000,12.26,1.97
127081,19119,SDS011,56.972,24.132,1546343793000000000,10.84,3.66
127082,19207,SDS011,59.466,18.036,1546343900000000000,5.74,2.40
127083,19301,SDS011,59.362,12.152,1546343810000000000,0.02,0.00
127084,7273,SDS011,60.002,17.846,1546343974000000000,2.63,1.30
127085,11232,SDS011,55.596,13.022,1546343986000000000,16.80,4.07
127086,11374,SDS011,59.258,18.008,1546343980000000000,6.35,4.08
127087,11378,SDS011,59.392,16.748,1546343987000000000,1.25,0.64
127088,11445,SDS011,64.178,15.432,1546343991000000000,0.45,0.26
127089,11546,SDS011,59.456,17.802,1546343985000000000,1.42,0.86
127090,11663,SDS011,59.380,18.040,1546343988000000000,1.77,1.10
127091,11769,SDS011,59.238,18.226,1546343996000000000,2.49,1.35
127092,12383,SDS011,63.808,20.336,1546343980000000000,2.13,0.65
127093,12387,SDS011,58.560,15.306,1546343992000000000,1.10,0.65
127094,12673,SDS011,59.364,18.022,1546343989000000000,2.63,1.50
127095,12675,SDS011,59.450,17.892,1546343987000000000,3.30,1.52
127096,12691,SDS011,57.636,18.304,1546343995000000000,5.25,1.94
127097,12990,SDS011,57.692,11.958,1546343880000000000,16.63,3.60
127098,13012,SDS011,57.662,12.006,1546343998000000000,8.18,2.25
127099,13020,SDS011,57.722,11.948,1546343981000000000,20.64,3.67
127100,16147,SDS011,59.364,18.018,1546343986000000000,3.28,1.80
127101,16153,SDS011,55.648,13.208,1546343839000000000,20.00,3.90
127102,16296,SDS011,56.144,13.394,1546343999000000000,23.86,7.45
127103,16533,SDS011,55.722,13.202,1546343815000000000,18.05,4.33
127104,16723,SDS011,57.736,11.894,1546343937000000000,16.47,3.40
127105,16815,SDS011,59.462,18.040,1546343976000000000,2.67,1.97
127106,17235,SDS011,59.272,17.780,1546343981000000000,4.69,1.82
127107,10588,SDS011,55.676,13.346,1546343832000000000,14.08,3.68
127108,10647,SDS011,55.608,13.036,1546343922000000000,23.42,4.75

In [49]:
# work with the csv loaded data

In [50]:
in_data.dtypes

sensor_id         int64
sensor_namee     object
lat             float64
lon             float64
timestamp         int64
p1              float64
p2              float64
dtype: object

In [51]:
# just to repeat this, so we don't forget it 
in_data['timestamp'] = pd.to_datetime( in_data['timestamp'] )

In [52]:
in_data

,sensor_id,sensor_namee,lat,lon,timestamp,p1,p2
0,7273,SDS011,60.002,17.846,2018-12-31 11:57:22,3.43,1.56
1,7275,SDS011,57.720,11.888,2018-12-31 11:58:44,482.77,33.82
2,7277,SDS011,59.266,15.230,2018-12-31 11:58:47,5.48,2.47
3,7406,SDS011,56.964,24.128,2018-12-31 11:56:41,11.05,6.62
4,7428,SDS011,59.868,17.624,2018-12-31 11:57:42,1.78,1.02
5,7469,SDS011,56.944,24.142,2018-12-31 11:57:52,8.40,5.54
6,7597,SDS011,59.320,18.064,2018-12-31 11:58:51,3.68,2.00
7,8683,SDS011,59.744,18.206,2018-12-31 11:58:28,3.01,2.80
8,9411,SDS011,59.266,15.230,2018-12-31 11:57:18,3.44,2.18
9,9436,SDS011,59.334,18.034,2018-12-31 11:57:22,2.12,1.90
10,9743,SDS011,57.664,12.054,2018-12-31 11:57:15,268.58,29.05
11,9797,SDS011,57.492,12.652,2018-12-31 11:58:52,10.13,7.05
12,10216,SDS011,59.674,16.838,2018-12-31 11:57:28,3.94,2.75
13,10250,SDS011,58.692,12.478,2018-12-31 11:58:38,11.55,5.88
14,10281,SDS011,59.472,18.048,2018-12-31 11:58:42,5.18,3.12
15,10430,SDS011,59.958,17.726,2018-12-31 11:57:35,2.42,1.58
16,10647,SDS011,55.608,13.036,2018-12-31 11:58:28,14.65,5.10
17,10721,SDS011,59.450,18.124,2018-12-31 11:57:54,2.28,1.45
18,10723,SDS011,59.298,18.052,2018-12-31 11:56:45,4.90,2.76
19,10803,SDS011,57.690,11.954,2018-12-31 11:58:07,31.01,6.02
20,10823,SDS011,59.332,18.034,2018-12-31 11:57:37,3.78,2.05
21,10825,SDS011,55.898,14.094,2018-12-31 11:57:55,9.50,7.00
22,10827,SDS011,59.334,13.512,2018-12-31 11:56:40,11.45,6.00
23,10843,SDS011,59.354,18.364,2018-12-31 11:58:46,5.44,2.13
24,10914,SDS011,61.450,23.858,2018-12-31 11:58:48,1.97,1.88
25,10922,SDS011,59.494,17.976,2018-12-31 11:57:26,5.75,3.05
26,10924,SDS011,59.860,17.652,2018-12-31 11:56:44,2.58,1.16
27,10926,SDS011,59.472,18.304,2018-12-31 11:57:06,3.26,2.35
28,11002,SDS011,55.796,13.090,2018-12-31 11:58:37,6.34,3.08
29,11004,SDS011,59.622,16.556,2018-12-31 11:58:53,4.40,1.95
...,...,...,...,...,...,...,...
127079,18826,SDS011,63.404,13.016,2019-01-01 11:59:35,11.82,1.67
127080,18836,SDS011,63.404,13.030,2019-01-01 11:59:39,12.26,1.97
127081,19119,SDS011,56.972,24.132,2019-01-01 11:56:33,10.84,3.66
127082,19207,SDS011,59.466,18.036,2019-01-01 11:58:20,5.74,2.40
127083,19301,SDS011,59.362,12.152,2019-01-01 11:56:50,0.02,0.00
127084,7273,SDS011,60.002,17.846,2019-01-01 11:59:34,2.63,1.30
127085,11232,SDS011,55.596,13.022,2019-01-01 11:59:46,16.80,4.07
127086,11374,SDS011,59.258,18.008,2019-01-01 11:59:40,6.35,4.08
127087,11378,SDS011,59.392,16.748,2019-01-01 11:59:47,1.25,0.64
127088,11445,SDS011,64.178,15.432,2019-01-01 11:59:51,0.45,0.26
127089,11546,SDS011,59.456,17.802,2019-01-01 11:59:45,1.42,0.86
127090,11663,SDS011,59.380,18.040,2019-01-01 11:59:48,1.77,1.10
127091,11769,SDS011,59.238,18.226,2019-01-01 11:59:56,2.49,1.35
127092,12383,SDS011,63.808,20.336,2019-01-01 11:59:40,2.13,0.65
127093,12387,SDS011,58.560,15.306,2019-01-01 11:59:52,1.10,0.65
127094,12673,SDS011,59.364,18.022,2019-01-01 11:59:49,2.63,1.50
127095,12675,SDS011,59.450,17.892,2019-01-01 11:59:47,3.30,1.52
127096,12691,SDS011,57.636,18.304,2019-01-01 11:59:55,5.25,1.94
127097,12990,SDS011,57.692,11.958,2019-01-01 11:58:00,16.63,3.60
127098,13012,SDS011,57.662,12.006,2019-01-01 11:59:58,8.18,2.25
127099,13020,SDS011,57.722,11.948,2019-01-01 11:59:41,20.64,3.67
127100,16147,SDS011,59.364,18.018,2019-01-01 11:59:46,3.28,1.80
127101,16153,SDS011,55.648,13.208,2019-01-01 11:57:19,20.00,3.90
127102,16296,SDS011,56.144,13.394,2019-01-01 11:59:59,23.86,7.45
127103,16533,SDS011,55.722,13.202,2019-01-01 11:56:55,18.05,4.33
127104,16723,SDS011,57.736,11.894,2019-01-01 11:58:57,16.47,3.40
127105,16815,SDS011,59.462,18.040,2019-01-01 11:59:36,2.67,1.97
127106,17235,SDS011,59.272,17.780,2019-01-01 11:59:41,4.69,1.82
127107,10588,SDS011,55.676,13.346,2019-01-01 11:57:12,14.08,3.68
127108,10647,SDS011,55.608,13.036,2019-01-01 11:58:42,23.42,4.75

In [53]:
start_time = "2018-12-31 21:58:42"
end_time = "2019-01-01 11:58:42"

In [54]:
in_data.shape

(127109, 7)

In [55]:
relevant_period = in_data[  in_data['timestamp'] > start_time ] 
relevant_period = relevant_period[  relevant_period['timestamp'] < end_time ] 
relevant_period.shape

(48799, 7)

In [56]:
relevant_period

,sensor_id,sensor_namee,lat,lon,timestamp,p1,p2
78090,7277,SDS011,59.266,15.230,2018-12-31 21:58:49,11.11,3.52
78094,7499,SDS011,59.924,10.738,2018-12-31 21:59:01,17.81,4.43
78095,7597,SDS011,59.320,18.064,2018-12-31 21:58:51,75.32,39.88
78109,11380,SDS011,55.606,12.998,2018-12-31 21:58:56,11.02,3.71
78122,11763,SDS011,56.522,14.950,2018-12-31 21:58:54,5.78,2.53
78129,12385,SDS011,57.634,18.310,2018-12-31 21:58:44,6.73,4.57
78132,12391,SDS011,59.860,17.640,2018-12-31 21:58:54,7.41,3.33
78134,12120,SDS011,59.460,17.908,2018-12-31 21:58:49,17.26,8.48
78136,12127,SDS011,57.702,11.904,2018-12-31 21:58:44,6.85,2.56
78146,12691,SDS011,57.636,18.304,2018-12-31 21:59:00,3.81,2.45
78148,12861,SDS011,66.348,14.134,2018-12-31 21:58:46,12.69,5.69
78159,14209,SDS011,56.070,12.698,2018-12-31 21:59:01,14.72,4.65
78174,16531,SDS011,57.698,11.958,2018-12-31 21:59:00,5.33,2.85
78179,16723,SDS011,57.736,11.894,2018-12-31 21:58:55,34.88,5.66
78180,13419,SDS011,58.440,15.470,2018-12-31 21:58:50,6.28,2.39
78187,13475,SDS011,63.824,20.288,2018-12-31 21:58:54,3.08,0.98
78195,14807,SDS011,57.718,12.034,2018-12-31 21:58:52,22.82,5.74
78212,16296,SDS011,56.144,13.394,2018-12-31 21:58:55,13.27,5.37
78215,18243,SDS011,55.674,13.072,2018-12-31 21:58:57,15.98,5.65
78220,17038,SDS011,55.750,13.202,2018-12-31 21:58:50,21.09,8.81
78233,18056,SDS011,57.494,12.166,2018-12-31 21:59:01,25.19,5.50
78242,19337,SDS011,59.396,16.474,2018-12-31 21:58:53,8.51,2.55
78256,10914,SDS011,61.450,23.858,2018-12-31 21:58:45,4.69,3.20
78261,11004,SDS011,59.622,16.556,2018-12-31 21:58:53,9.50,2.51
78264,7406,SDS011,56.964,24.128,2018-12-31 22:00:05,11.76,6.74
78265,7273,SDS011,60.002,17.846,2018-12-31 22:01:06,13.94,5.76
78266,7275,SDS011,57.720,11.888,2018-12-31 21:59:39,26.70,6.40
78267,7277,SDS011,59.266,15.230,2018-12-31 22:01:18,9.64,3.40
78268,7428,SDS011,59.868,17.624,2018-12-31 22:01:50,6.42,2.30
78269,7469,SDS011,56.944,24.142,2018-12-31 22:00:35,13.50,7.14
...,...,...,...,...,...,...,...
127034,16147,SDS011,59.364,18.018,2019-01-01 11:57:14,1.92,1.65
127035,16149,SDS011,55.606,13.024,2019-01-01 11:56:40,14.90,2.67
127037,16153,SDS011,55.648,13.208,2019-01-01 11:57:19,21.05,4.22
127038,16155,SDS011,59.832,17.632,2019-01-01 11:57:44,3.33,1.65
127039,16159,SDS011,57.818,15.224,2019-01-01 11:56:49,4.42,1.08
127040,16296,SDS011,56.144,13.394,2019-01-01 11:57:30,25.28,7.05
127041,16811,SDS011,59.368,18.016,2019-01-01 11:57:32,3.35,1.21
127042,16815,SDS011,59.462,18.040,2019-01-01 11:56:46,3.55,2.04
127043,17018,SDS011,55.718,13.234,2019-01-01 11:58:37,19.52,2.50
127044,17020,SDS011,55.728,13.194,2019-01-01 11:57:00,27.82,5.70
127045,17038,SDS011,55.750,13.202,2019-01-01 11:57:39,15.37,3.24
127047,18110,SDS011,57.490,12.078,2019-01-01 11:57:27,14.68,4.15
127048,18112,SDS011,57.478,11.978,2019-01-01 11:56:36,25.70,4.85
127050,18820,SDS011,59.332,18.034,2019-01-01 11:57:43,4.07,1.74
127051,18826,SDS011,63.404,13.016,2019-01-01 11:57:06,8.64,1.28
127052,18836,SDS011,63.404,13.030,2019-01-01 11:57:10,12.83,1.94
127053,18838,SDS011,56.920,14.804,2019-01-01 11:58:00,6.62,1.46
127054,18986,SDS011,59.236,18.142,2019-01-01 11:58:13,2.70,1.12
127055,19337,SDS011,59.396,16.474,2019-01-01 11:58:32,1.93,0.73
127056,19547,SDS011,58.014,11.826,2019-01-01 11:58:17,4.10,1.20
127057,19597,SDS011,59.308,18.108,2019-01-01 11:57:43,2.80,0.65
127058,19599,SDS011,57.722,12.012,2019-01-01 11:56:39,22.35,4.12
127067,14290,SDS011,57.730,11.930,2019-01-01 11:57:13,11.70,3.00
127081,19119,SDS011,56.972,24.132,2019-01-01 11:56:33,10.84,3.66
127082,19207,SDS011,59.466,18.036,2019-01-01 11:58:20,5.74,2.40
127083,19301,SDS011,59.362,12.152,2019-01-01 11:56:50,0.02,0.00
127097,12990,SDS011,57.692,11.958,2019-01-01 11:58:00,16.63,3.60
127101,16153,SDS011,55.648,13.208,2019-01-01 11:57:19,20.00,3.90
127103,16533,SDS011,55.722,13.202,2019-01-01 11:56:55,18.05,4.33
127107,10588,SDS011,55.676,13.346,2019-01-01 11:57:12,14.08,3.68

In [57]:
relevant_period['timestamp'] = in_data['timestamp'].astype( 'int64' )

In [58]:
relevant_period

,sensor_id,sensor_namee,lat,lon,timestamp,p1,p2
78090,7277,SDS011,59.266,15.230,1546293529000000000,11.11,3.52
78094,7499,SDS011,59.924,10.738,1546293541000000000,17.81,4.43
78095,7597,SDS011,59.320,18.064,1546293531000000000,75.32,39.88
78109,11380,SDS011,55.606,12.998,1546293536000000000,11.02,3.71
78122,11763,SDS011,56.522,14.950,1546293534000000000,5.78,2.53
78129,12385,SDS011,57.634,18.310,1546293524000000000,6.73,4.57
78132,12391,SDS011,59.860,17.640,1546293534000000000,7.41,3.33
78134,12120,SDS011,59.460,17.908,1546293529000000000,17.26,8.48
78136,12127,SDS011,57.702,11.904,1546293524000000000,6.85,2.56
78146,12691,SDS011,57.636,18.304,1546293540000000000,3.81,2.45
78148,12861,SDS011,66.348,14.134,1546293526000000000,12.69,5.69
78159,14209,SDS011,56.070,12.698,1546293541000000000,14.72,4.65
78174,16531,SDS011,57.698,11.958,1546293540000000000,5.33,2.85
78179,16723,SDS011,57.736,11.894,1546293535000000000,34.88,5.66
78180,13419,SDS011,58.440,15.470,1546293530000000000,6.28,2.39
78187,13475,SDS011,63.824,20.288,1546293534000000000,3.08,0.98
78195,14807,SDS011,57.718,12.034,1546293532000000000,22.82,5.74
78212,16296,SDS011,56.144,13.394,1546293535000000000,13.27,5.37
78215,18243,SDS011,55.674,13.072,1546293537000000000,15.98,5.65
78220,17038,SDS011,55.750,13.202,1546293530000000000,21.09,8.81
78233,18056,SDS011,57.494,12.166,1546293541000000000,25.19,5.50
78242,19337,SDS011,59.396,16.474,1546293533000000000,8.51,2.55
78256,10914,SDS011,61.450,23.858,1546293525000000000,4.69,3.20
78261,11004,SDS011,59.622,16.556,1546293533000000000,9.50,2.51
78264,7406,SDS011,56.964,24.128,1546293605000000000,11.76,6.74
78265,7273,SDS011,60.002,17.846,1546293666000000000,13.94,5.76
78266,7275,SDS011,57.720,11.888,1546293579000000000,26.70,6.40
78267,7277,SDS011,59.266,15.230,1546293678000000000,9.64,3.40
78268,7428,SDS011,59.868,17.624,1546293710000000000,6.42,2.30
78269,7469,SDS011,56.944,24.142,1546293635000000000,13.50,7.14
...,...,...,...,...,...,...,...
127034,16147,SDS011,59.364,18.018,1546343834000000000,1.92,1.65
127035,16149,SDS011,55.606,13.024,1546343800000000000,14.90,2.67
127037,16153,SDS011,55.648,13.208,1546343839000000000,21.05,4.22
127038,16155,SDS011,59.832,17.632,1546343864000000000,3.33,1.65
127039,16159,SDS011,57.818,15.224,1546343809000000000,4.42,1.08
127040,16296,SDS011,56.144,13.394,1546343850000000000,25.28,7.05
127041,16811,SDS011,59.368,18.016,1546343852000000000,3.35,1.21
127042,16815,SDS011,59.462,18.040,1546343806000000000,3.55,2.04
127043,17018,SDS011,55.718,13.234,1546343917000000000,19.52,2.50
127044,17020,SDS011,55.728,13.194,1546343820000000000,27.82,5.70
127045,17038,SDS011,55.750,13.202,1546343859000000000,15.37,3.24
127047,18110,SDS011,57.490,12.078,1546343847000000000,14.68,4.15
127048,18112,SDS011,57.478,11.978,1546343796000000000,25.70,4.85
127050,18820,SDS011,59.332,18.034,1546343863000000000,4.07,1.74
127051,18826,SDS011,63.404,13.016,1546343826000000000,8.64,1.28
127052,18836,SDS011,63.404,13.030,1546343830000000000,12.83,1.94
127053,18838,SDS011,56.920,14.804,1546343880000000000,6.62,1.46
127054,18986,SDS011,59.236,18.142,1546343893000000000,2.70,1.12
127055,19337,SDS011,59.396,16.474,1546343912000000000,1.93,0.73
127056,19547,SDS011,58.014,11.826,1546343897000000000,4.10,1.20
127057,19597,SDS011,59.308,18.108,1546343863000000000,2.80,0.65
127058,19599,SDS011,57.722,12.012,1546343799000000000,22.35,4.12
127067,14290,SDS011,57.730,11.930,1546343833000000000,11.70,3.00
127081,19119,SDS011,56.972,24.132,1546343793000000000,10.84,3.66
127082,19207,SDS011,59.466,18.036,1546343900000000000,5.74,2.40
127083,19301,SDS011,59.362,12.152,1546343810000000000,0.02,0.00
127097,12990,SDS011,57.692,11.958,1546343880000000000,16.63,3.60
127101,16153,SDS011,55.648,13.208,1546343839000000000,20.00,3.90
127103,16533,SDS011,55.722,13.202,1546343815000000000,18.05,4.33
127107,10588,SDS011,55.676,13.346,1546343832000000000,14.08,3.68

In [59]:
relevant_period.index

Int64Index([ 78090,  78094,  78095,  78109,  78122,  78129,  78132,  78134,
             78136,  78146,
            ...
            127057, 127058, 127067, 127081, 127082, 127083, 127097, 127101,
            127103, 127107],
           dtype='int64', length=48799)

In [60]:
# create an array to store the results in 
out_array = np.zeros( time_date_range_as_epoch.shape[0] )

In [61]:
out_array.shape

(289,)

In [62]:
# create an array of values for the given sensor, 
# filling in possible blank areas with zeros ( well, by not adding anything there )

In [67]:
starttime = time.time()
out = []
for row_i in range( relevant_period.shape[0] ):
    relev_time = int( relevant_period.iloc[ row_i ]['timestamp'] ) 
#     print( type( relev_time ))
#     print( relev_time.shape )
#     out_array[row_i] = relev_time
    
print( "--- well, that took "+str( time.time() - starttime ) )

--- well, that took 7.024564981460571

In [ ]:
relevant_period[0:1].shape

In [ ]:
two = relevant_period[0:1]['timestamp']
two

In [ ]:
relevant_period.loc[[2]]

In [ ]:
relevant_period.loc[3]

In [ ]:
relevant_period[0:1]

In [ ]:
relevant_period[1:2]

In [ ]:
relevant_period.at[0]

In [ ]:
relevant_period[:20]

In [ ]:

one = int( relevant_period[20:21]['p1'] )

In [ ]:
one

In [ ]:
relevant_period[20:21]['timestamp']

In [ ]:
float( relevant_period[20:21]['p1'] )

In [ ]:
type( relevant_period['timestamp'] )

In [ ]:
relevant_period['timestamp'].iloc[1]

In [ ]:
relevant_period['timestamp'].iloc[3]

In [ ]:
relevant_period.iloc[0]

In [ ]:
relevant_period.iloc[1]

In [ ]:
relevant_period.iloc[2]

In [ ]:
relevant_period.shape

In [ ]:
# turn the timestamp column into an epoch column 
relevant_period['timestamp'] = relevant_period['timestamp'].astype( 'int64' )

In [ ]:
# extract data just for one sensor
relevant_period__single_sensor = relevant_period[ relevant_period['sensor_id'] == 7597  ]

In [ ]:
relevant_period__single_sensor.shape

In [ ]:
starttime = time.time()
out = 0
out_time = 0
for index in range( relevant_period__single_sensor.shape[0] ) :
    out = relevant_period__single_sensor.iloc[ index ]['p1']
    out_time = relevant_period__single_sensor.iloc[ index ]['timestamp']
#     print( "index : "+str( index ) )
#     print( relevant_period.iloc[ index ] )
    # check if the the relevant measurment ( in the variable above ) is within the 
    # relevant time period.
    # - loop through the time range and see if the current timestamp is within that

print(' well, that took '+str( time.time() - starttime )+' seconds  ')

In [ ]:


# try convert the timestamp in the data, to epoch

in_data = pd.read_csv( "/Users/miska/Documents/open_something/luftdaten/luftdaten_code/luftdaten__make_tabular_data__from_db_data/ld_NYE_midnight_24hrs_nordics_all_data_01.csv" )

In [ ]:
in_ = in_data['timestamp']

In [ ]:
type( in_ )

In [ ]:
in_[0]

In [ ]:
for row in in_[:10]:
    print( row )

In [ ]:
for row in in_data[:10]:
    print( row )

In [ ]:
unique_vals_for_sensor_id_7273 = in_data[ in_data['sensor_id'] == 7273  ]

In [ ]:
unique_vals_for_sensor_id_7273.shape

In [ ]:
unique_vals_for_sensor_id_7273

In [ ]:
unique_vals_for_sensor_id_7273.iloc[2]

In [ ]:
for row_i in range( unique_vals_for_sensor_id_7273.shape[0] ):
    print( unique_vals_for_sensor_id_7273.iloc[ row_i] )